import React from 'react'
import ReactDOM from 'react-dom/client'
import Root from './Root'
import './styles.css'
import './plot-enhancements.css'
import './design.css'
import './workbench.css'
import './worker-health.css'
import './language.css'
import './project-workspace.css'
import './result-artifacts.css'
import './eda-visualizations.css'
import './library-cards.css'
import './pages.css'

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><Root /></React.StrictMode>)
