import { text as t, type Category, type Config, type Device, type DeviceId, type Guide, type Parameter, type Text } from './types'

export const REFERENCES: Record<string, { title: string; url: string }> = {
  devices: { title: 'MIT 6.012 · Microelectronic Devices and Circuits', url: 'https://ocw.mit.edu/courses/6-012-microelectronic-devices-and-circuits-spring-2009/pages/lecture-notes/' },
  fabrication: { title: 'MIT 6.774 · Physics of Microfabrication', url: 'https://ocw.mit.edu/courses/6-774-physics-of-microfabrication-front-end-processing-fall-2004/' },
  pv: { title: 'PVEducation · Solar cell operation', url: 'https://www.pveducation.org/pvcdrom/solar-cell-operation/solar-cell-operation' },
  constants: { title: 'NIST · SI and fundamental constants', url: 'https://physics.nist.gov/cuu/Constants/' },
  devsim: { title: 'DEVSIM · Semiconductor device simulator', url: 'https://devsim.org/' },
  oxidation: { title: 'Deal & Grove (1965) · General Relationship for the Thermal Oxidation of Silicon', url: 'https://doi.org/10.1063/1.1713945' },
}
export const CATEGORIES: Record<Category, Text> = {
  foundations: t('Materia y portadores', 'Matter and carriers'), diodes: t('Diodos y uniones', 'Diodes and junctions'),
  transistors: t('Transistores y control', 'Transistors and control'), opto: t('Luz y semiconductores', 'Light and semiconductors'),
  circuits: t('Circuitos y señales', 'Circuits and signals'), fabrication: t('Fabricación y rendimiento', 'Fabrication and yield'),
}
const p = (key: string, es: string, en: string, unit: string, value: number, min: number, max: number, log = false, intro = false): Parameter => ({ key, label: t(es, en), unit, default: value, min, max, log, intro })
const temperature = p('temperature', 'Temperatura', 'Temperature', 'K', 300, 200, 450, false, true)
const na = p('na', 'Aceptores NA (lado P)', 'Acceptors NA (P side)', 'cm⁻³', 1e16, 1e13, 1e19, true, true)
const nd = p('nd', 'Donantes ND (lado N)', 'Donors ND (N side)', 'cm⁻³', 1e16, 1e13, 1e19, true, true)
const area = p('area', 'Área activa', 'Active area', 'µm²', 100, 1, 1e8, true)
const bias = p('bias', 'Tensión de observación', 'Observation bias', 'V', 0, -10, .75, false, true)
const ideality = p('ideality', 'Factor de idealidad', 'Ideality factor', '1', 1, 1, 3)
const saturation = p('isat', 'Corriente de saturación Is', 'Saturation current Is', 'A', 1e-12, 1e-18, 1e-6, true)
const start = p('start', 'Inicio del barrido', 'Sweep start', 'V', -.5, -20, 10)
const stop = p('stop', 'Fin del barrido', 'Sweep end', 'V', .7, -19, 20)
const tau = p('tau', 'Vida media de portadores', 'Carrier lifetime', 'ns', 100, .01, 1e6, true)
const diodeParameters = [temperature, na, nd, area, bias, ideality, saturation, start, stop]
const transistorParameters = [temperature, p('beta', 'Ganancia β directa', 'Forward gain β', '1', 100, 5, 500, false, true), p('beta_reverse', 'Ganancia β inversa', 'Reverse gain β', '1', 2, .1, 20), saturation, p('vbe', 'Tensión base–emisor (magnitud)', 'Base–emitter voltage (magnitude)', 'V', .65, 0, .85, false, true), p('early', 'Tensión de Early', 'Early voltage', 'V', 100, 10, 500), { ...start, default: 0, min: 0 }, { ...stop, default: 5, min: .1 }]
const mosParameters = [temperature, p('threshold', 'Umbral |Vth|', 'Threshold |Vth|', 'V', .7, .1, 3, false, true), p('gate', 'Tensión de puerta (magnitud)', 'Gate voltage (magnitude)', 'V', 1.8, 0, 6, false, true), p('drain', 'Tensión de drenador (magnitud)', 'Drain voltage (magnitude)', 'V', 1.8, .001, 10), p('mobility', 'Movilidad efectiva μ', 'Effective mobility μ', 'cm²/(V·s)', 450, 10, 1500), p('width', 'Ancho W', 'Width W', 'µm', 10, .1, 1000, true), p('length', 'Longitud L', 'Length L', 'µm', 2, .5, 100, true), p('oxide', 'Espesor de óxido', 'Oxide thickness', 'nm', 20, 5, 500, true), p('lambda', 'Modulación λ', 'Channel modulation λ', 'V⁻¹', .02, 0, .2), { ...start, default: 0, min: 0 }, { ...stop, default: 3, min: .1 }]
const resistor = p('resistance', 'Resistencia R', 'Resistance R', 'Ω', 1000, 1, 1e7, true, true)
const capacitance = p('capacitance', 'Capacitancia C', 'Capacitance C', 'nF', 100, .001, 1e6, true, true)
const seconds = p('time', 'Duración del experimento', 'Experiment duration', 's', 600, 1, 1e5, true, true)
const depth = p('depth', 'Profundidad de observación', 'Observation depth', 'µm', 2, .05, 100, true)
const diffusionCoefficient = p('diffusivity', 'Coeficiente D a la temperatura del proceso', 'Diffusivity D at process temperature', 'µm²/s', 1e-4, 1e-8, 1, true, true)
const device = (id: DeviceId, category: Category, es: string, en: string, symbol: string, summary: Text, story: Text, parameters: Parameter[], equations: string[], assumptions: Text[], references = ['devices', 'constants']): Device => ({ id, category, name: t(es, en), symbol, summary, story, parameters, equations, assumptions, references })
const compact = t('Modelo compacto idealizado con parámetros editables; no está calibrado a un componente comercial.', 'Idealized compact model with editable parameters; not calibrated to a commercial component.')
const silicon = t('Silicio no degenerado, dopaje uniforme, movilidad de bajo campo; la alta inyección, la ruptura y el calentamiento quedan fuera del modelo.', 'Nondegenerate silicon, uniform doping, low-field mobility; high injection, breakdown and self-heating are outside the model.')

export const DEVICES: Device[] = [
  device('material', 'foundations', 'Silicio y dopaje', 'Silicon and doping', 'Si', t('Concentraciones, conductividad y temperatura.', 'Concentrations, conductivity and temperature.'), t('Un hueco es un lugar disponible para un electrón: al llenarlo, el lugar vacío parece moverse.', 'A hole is a place available to an electron: when it fills, the empty place appears to move.'), [temperature, na, nd], ['np = ni²', 'n − p = ND − NA', 'σ = q(μn n + μp p)'], [silicon]),
  device('transport', 'foundations', 'Deriva y difusión', 'Drift and diffusion', 'n/p', t('Separe los mecanismos del transporte.', 'Separate transport mechanisms.'), t('Los portadores se dispersan desde donde abundan y también responden a un campo eléctrico.', 'Carriers spread from crowded regions and also respond to an electric field.'), [temperature, nd, p('field', 'Campo eléctrico E', 'Electric field E', 'V/cm', 100, -5000, 5000, false, true), p('gradient', 'Gradiente dn/dx', 'Gradient dn/dx', 'cm⁻⁴', -5e19, -1e22, 1e22), tau, depth], ['Jn = q μn n E + q Dn dn/dx', 'Dn/μn = kT/q', 'Ln = √(Dn τ)'], [silicon]),
  device('resistor', 'foundations', 'Resistor semiconductor', 'Semiconductor resistor', 'R', t('De dopaje y geometría a resistencia.', 'From doping and geometry to resistance.'), t('Un camino largo y estrecho dificulta el paso; más portadores facilitan la conducción.', 'A long narrow path resists flow; more carriers help conduction.'), [temperature, nd, area, p('length', 'Longitud', 'Length', 'µm', 100, .1, 1e4, true, true), { ...start, default: -2 }, { ...stop, default: 2 }], ['R = L / [q μn ND A]', 'I = V/R', 'P = VI'], [silicon]),
  device('hall', 'foundations', 'Efecto Hall', 'Hall effect', 'B', t('Identifique signo y densidad de portadores.', 'Identify carrier sign and density.'), t('Un campo magnético desvía las cargas y crea una pequeña tensión lateral.', 'A magnetic field deflects charges and creates a small lateral voltage.'), [nd, p('current', 'Corriente longitudinal', 'Longitudinal current', 'mA', 1, .001, 100, true, true), p('thickness', 'Espesor', 'Thickness', 'µm', 10, .1, 1000, true), p('magnetic', 'Campo máximo B', 'Maximum field B', 'T', 1, .01, 5, false, true)], ['RH = −1/(q n)', 'VH = RH I B/t'], [t('Un único tipo de portador n, factor de Hall igual a 1 y campo uniforme.', 'Single n-type carrier, Hall factor 1 and uniform field.')]),
  device('pn', 'diodes', 'Unión PN', 'PN junction', 'P|N', t('Electrostática, portadores, bandas, I–V y C–V.', 'Electrostatics, carriers, bands, I–V and C–V.'), t('Al unir dos regiones se crea una barrera. La tensión puede facilitar o dificultar el cruce.', 'Joining two regions creates a barrier. Voltage can help or hinder crossing.'), diodeParameters, ['Vbi = VT ln(NA ND/ni²)', 'W = √[(2ε/q)(1/NA + 1/ND)(Vbi − V)]', 'I = Is[exp(V/(n VT)) − 1]'], [silicon, t('Aproximación de agotamiento abrupto. La I–V usa Is y n explícitos, independientes de los perfiles electrostáticos.', 'Abrupt depletion approximation. I–V uses explicit Is and n, independent of electrostatic profiles.')], ['devices', 'devsim', 'constants']),
  device('pin', 'diodes', 'Diodo PIN', 'PIN diode', 'P|I|N', t('Región intrínseca, campo y tiempo de tránsito.', 'Intrinsic region, field and transit time.'), t('Una zona central casi vacía ensancha la barrera y reduce la capacitancia.', 'A nearly empty central region widens the barrier and reduces capacitance.'), [...diodeParameters, p('intrinsic', 'Espesor intrínseco', 'Intrinsic thickness', 'µm', 2, .1, 100, true, true)], ['Vbi − V = q NA xp²/(2ε) + E wi + q ND xn²/(2ε)', 'NA xp = ND xn', 'C = ε A/(xp + wi + xn)'], [silicon, t('Capa I totalmente agotada, sin dopaje residual ni modulación de conductividad.', 'Fully depleted I layer, without residual doping or conductivity modulation.')]),
  device('zener', 'diodes', 'Zener / avalancha', 'Zener / avalanche', 'Z', t('Ruptura inversa y resistencia dinámica.', 'Reverse breakdown and dynamic resistance.'), t('En inversa, este diodo puede mantener una tensión casi fija al circular corriente.', 'In reverse bias this diode can hold nearly constant voltage while current flows.'), [...diodeParameters.map(x => x.key === 'start' ? { ...x, default: -8 } : x), p('breakdown', 'Tensión de ruptura |Vz|', 'Breakdown voltage |Vz|', 'V', 5.1, 2, 15, false, true), p('dynamic', 'Resistencia dinámica en ruptura', 'Breakdown dynamic resistance', 'Ω', 20, 1, 1000, true)], ['I(V < −Vz) = (V + Vz)/rz', 'P = |VI|'], [compact, t('La rama de ruptura es lineal; no resuelve ionización por impacto ni túnel cuántico.', 'The breakdown branch is linear; it does not solve impact ionization or quantum tunneling.')]),
  device('schottky', 'diodes', 'Contacto Schottky', 'Schottky contact', 'M|N', t('Emisión termoiónica y barrera metal–semiconductor.', 'Thermionic emission and metal–semiconductor barrier.'), t('Un metal también puede crear una barrera con un semiconductor.', 'A metal can also form a barrier with a semiconductor.'), [temperature, area, ideality, p('barrier', 'Altura de barrera ΦB', 'Barrier height ΦB', 'eV', .7, .3, 1.2, false, true), { ...start, default: -.5 }, { ...stop, default: .5 }, p('richardson', 'Constante de Richardson A*', 'Richardson constant A*', 'A/(cm²·K²)', 112, 1, 200)], ['Is = A A* T² exp(−ΦB/VT)', 'I = Is[exp(V/(n VT)) − 1]'], [compact, t('Emisión termoiónica ideal; sin reducción de barrera, estados de interfaz ni resistencia serie.', 'Ideal thermionic emission; no barrier lowering, interface states or series resistance.')]),
  device('varactor', 'diodes', 'Varactor', 'Varactor', 'C(V)', t('Capacitancia controlada por tensión.', 'Voltage-controlled capacitance.'), t('Al ensanchar la zona sin portadores, disminuye la capacitancia.', 'Widening the carrier-depleted region lowers capacitance.'), [temperature, na, nd, area, p('reverse', 'Tensión inversa máxima', 'Maximum reverse voltage', 'V', 10, .1, 20, false, true)], ['C(VR) = C0/√(1 + VR/Vbi)', '1/C² ∝ Vbi + VR'], [silicon, t('Unión abrupta en inversa, sin resistencia serie ni ruptura.', 'Abrupt reverse-biased junction without series resistance or breakdown.')]),
  device('tunnel', 'diodes', 'Diodo túnel', 'Tunnel diode', 'NDR', t('Región de resistencia diferencial negativa.', 'Negative differential resistance region.'), t('En cierto intervalo, aumentar la tensión puede disminuir la corriente.', 'Over one interval, increasing voltage can decrease current.'), [p('peak', 'Tensión de pico Vp', 'Peak voltage Vp', 'V', .1, .03, .3, false, true), p('peak_current', 'Corriente de pico Ip', 'Peak current Ip', 'mA', 5, .1, 100), { ...stop, default: .6, min: .2, max: 1 }], ['Itunnel = Ip (V/Vp) exp(1 − V/Vp)', 'I = Itunnel + Idiffusion'], [t('Modelo fenomenológico de forma de curva; no calcula transmisión cuántica ni estructura de bandas degeneradas.', 'Phenomenological curve-shape model; does not calculate quantum transmission or degenerate band structure.')]),
  device('led', 'opto', 'LED', 'LED', 'hν↑', t('Corriente, fotones y potencia óptica.', 'Current, photons and optical power.'), t('Cuando un electrón llena un hueco, parte de la energía puede salir como luz.', 'When an electron fills a hole, some energy can leave as light.'), [temperature, { ...ideality, default: 2 }, { ...saturation, default: 1e-20, min: 1e-25 }, p('bandgap', 'Energía del fotón / banda efectiva', 'Photon energy / effective gap', 'eV', 1.9, 1, 3.5, false, true), p('efficiency', 'Eficiencia cuántica externa', 'External quantum efficiency', '%', 30, 0, 100, false, true), p('series_resistance', 'Resistencia serie', 'Series resistance', 'Ω', 20, 1, 1000), { ...stop, default: 3, min: .5, max: 5 }], ['V = n VT ln(1 + I/Is) + I Rs', 'λ = hc/Ephoton', 'Popt = EQE (I/q) Ephoton'], [compact, t('EQE y energía del fotón constantes. No simula espectro, estructura de pozos cuánticos ni eficiencia a alta corriente.', 'Constant EQE and photon energy. No spectral, quantum-well or high-current efficiency model.')]),
  device('photodiode', 'opto', 'Fotodiodo', 'Photodiode', 'hν↓', t('Responsividad, corriente oscura y ancho de banda.', 'Responsivity, dark current and bandwidth.'), t('La luz puede generar parejas electrón–hueco que producen corriente.', 'Light can generate electron–hole pairs that produce current.'), [temperature, saturation, p('power', 'Potencia óptica incidente', 'Incident optical power', 'µW', 10, 0, 1e5, false, true), p('wavelength', 'Longitud de onda', 'Wavelength', 'nm', 650, 400, 1100, false, true), p('efficiency', 'Eficiencia cuántica externa', 'External quantum efficiency', '%', 80, 0, 100), p('capacitance', 'Capacitancia de unión', 'Junction capacitance', 'pF', 10, .01, 1e4, true), resistor, { ...start, default: -5 }, { ...stop, default: .6 }], ['Rλ = EQE q λ/(hc)', 'I = Is[exp(V/VT) − 1] − Rλ P', 'fRC = 1/(2π R C)'], [compact, t('Responsividad constante a la longitud de onda elegida; el ancho de banda sólo incluye el polo RC.', 'Constant responsivity at the chosen wavelength; bandwidth includes only the RC pole.')], ['devices', 'pv', 'constants']),
  device('solar', 'opto', 'Celda solar', 'Solar cell', 'PV', t('I–V iluminada, potencia, MPP y factor de llenado.', 'Illuminated I–V, power, MPP and fill factor.'), t('La unión separa las cargas creadas por la luz y entrega energía a una carga externa.', 'The junction separates light-generated charges and delivers energy to an external load.'), [temperature, { ...saturation, default: 1e-10 }, { ...ideality, default: 1.2 }, p('photo_current', 'Corriente fotogenerada Isc', 'Photogenerated current Isc', 'mA', 30, .001, 1000, true, true), p('optical_input', 'Potencia luminosa incidente total', 'Total incident optical power', 'mW', 100, .01, 1e4, true, true)], ['Iout = Iph − Is[exp(V/(n VT)) − 1]', 'Voc = n VT ln(1 + Iph/Is)', 'FF = Pmpp/(Isc Voc)', 'η = Pmpp/Pin'], [compact, t('Una sola unión ideal, sin resistencias serie/paralelo ni respuesta espectral. Pin e Iph son entradas independientes.', 'Single ideal junction, no series/shunt resistance or spectral response. Pin and Iph are independent inputs.')], ['pv', 'devices', 'constants']),
  ...(['npn', 'pnp'] as const).map(id => device(id, 'transistors', `BJT ${id.toUpperCase()}`, `BJT ${id.toUpperCase()}`, id.toUpperCase(), t('Ebers–Moll, regiones de operación y ganancia.', 'Ebers–Moll, operating regions and gain.'), t('Una pequeña corriente de base controla una corriente mayor entre emisor y colector.', 'A small base current controls a larger current between emitter and collector.'), transistorParameters, ['IC = αF IF − IR', 'IB = (1 − αF) IF + (1 − αR) IR', 'IE = −IC − IB'], [compact, t('Ebers–Moll con reciprocidad y corrección de Early en activa; sin capacitancias, calentamiento ni ruptura.', 'Reciprocal Ebers–Moll with an active-region Early correction; no capacitance, self-heating or breakdown.')])),
  ...(['nmos', 'pmos'] as const).map(id => device(id, 'transistors', `MOSFET ${id === 'nmos' ? 'NMOS' : 'PMOS'}`, `MOSFET ${id === 'nmos' ? 'NMOS' : 'PMOS'}`, id === 'nmos' ? 'NMOS' : 'PMOS', t('Transferencia, salida, gm y regiones de operación.', 'Transfer, output, gm and operating regions.'), t('La puerta atrae portadores y forma un canal: una tensión controla otra corriente.', 'The gate attracts carriers and forms a channel: one voltage controls another current.'), mosParameters.map(x => id === 'pmos' && x.key === 'mobility' ? { ...x, default: 180 } : x), ['β = μ Cox W/L', 'ID,lin = β[(VGS − Vth)VDS − VDS²/2]', 'ID,sat = β(VGS − Vth)²(1 + λVDS)/2'], [compact, t('Canal largo, umbral fijo, corriente subumbral idealizada. PMOS usa magnitudes en controles y tensiones/corrientes negativas en curvas.', 'Long channel, fixed threshold, idealized subthreshold current. PMOS controls use magnitudes; curves use negative voltages and currents.') ])),
  device('jfet', 'transistors', 'JFET canal N', 'N-channel JFET', 'JFET', t('Pinzamiento, transferencia y curvas de salida.', 'Pinch-off, transfer and output curves.'), t('Una unión inversa estrecha el canal hasta cortar el paso de portadores.', 'A reverse-biased junction narrows the channel until carrier flow stops.'), [p('idss', 'Corriente IDSS', 'Current IDSS', 'mA', 10, .1, 100, true, true), p('pinch', 'Magnitud de pinzamiento |Vp|', 'Pinch-off magnitude |Vp|', 'V', 4, .5, 10), p('gate', 'Tensión VGS', 'Voltage VGS', 'V', -1, -10, 0, false, true), { ...stop, default: 8, min: 1 }], ['ID,sat = IDSS (1 − VGS/Vp)²', 'VDS,sat = VGS − Vp'], [compact, t('Canal N de agotamiento, sin corriente de puerta ni ruptura.', 'N-channel depletion device without gate current or breakdown.')]),
  device('moscap', 'transistors', 'Capacitor MOS', 'MOS capacitor', 'MOS C', t('Acumulación, agotamiento, inversión y C–V.', 'Accumulation, depletion, inversion and C–V.'), t('La puerta cambia las cargas de la superficie sin tocar directamente el silicio.', 'The gate changes surface charge without directly touching silicon.'), [temperature, na, area, p('oxide', 'Espesor de SiO₂', 'SiO₂ thickness', 'nm', 20, 5, 500, true, true), p('flatband', 'Tensión de banda plana Vfb', 'Flat-band voltage Vfb', 'V', -.2, -2, 2), { ...start, default: -2 }, { ...stop, default: 3 }], ['Vg = Vfb + ψs − Qs/Cox', 'Qs² = 2ε q VT[p0(exp(−u) + u − 1) + n0(exp(u) − u − 1)]', 'CLF = Cox Cs/(Cox + Cs)'], [silicon, t('MOS ideal sobre sustrato P, estadística de Boltzmann, carga superficial 1D. La C–V HF usa la aproximación de agotamiento máximo.', 'Ideal MOS on P substrate, Boltzmann statistics, 1D surface charge. HF C–V uses maximum-depletion approximation.')]),
  device('igbt', 'transistors', 'IGBT equivalente', 'Equivalent IGBT', 'IGBT', t('Control de puerta y caída de conducción.', 'Gate control and on-state voltage drop.'), t('Combina control por puerta con una caída de conducción de tipo bipolar.', 'Combines gate control with a bipolar-like on-state voltage drop.'), [p('gate', 'Tensión de puerta', 'Gate voltage', 'V', 10, 0, 20, false, true), p('threshold', 'Umbral de puerta', 'Gate threshold', 'V', 4, 1, 8), p('offset', 'Caída VCE0', 'Drop VCE0', 'V', 1.2, .2, 3), p('resistance', 'Resistencia equivalente encendido', 'Equivalent on resistance', 'Ω', .1, .01, 10, true), { ...stop, default: 5, min: 1, max: 20 }], ['Ion ≈ max(VCE − VCE0, 0)/Ron', 'I = Ion · clamp((VGE − Vth)/5, 0, 1)'], [t('Equivalente estático fenomenológico; no modela plasma, cola de apagado, área segura ni pérdidas de conmutación.', 'Phenomenological static equivalent; does not model plasma, turn-off tail, safe operating area or switching losses.')]),
  device('scr', 'transistors', 'Tiristor SCR', 'SCR thyristor', 'PNPN', t('Disparo, enclavamiento e histéresis de encendido.', 'Triggering, latching and turn-on hysteresis.'), t('Un pulso puede encenderlo; permanece activo mientras la corriente supere la de mantenimiento.', 'A pulse can switch it on; it stays on while current exceeds the holding current.'), [p('supply', 'Tensión máxima de alimentación', 'Maximum supply voltage', 'V', 20, 2, 100, false, true), p('trigger', 'Tensión del pulso de disparo en la rampa', 'Supply voltage at trigger pulse', 'V', 8, 1, 90, false, true), p('holding', 'Corriente de mantenimiento', 'Holding current', 'mA', 5, .1, 100), p('load', 'Resistencia de carga', 'Load resistance', 'Ω', 100, 10, 1e4, true)], ['I = max(Vs − Von, 0)/RL', 'Estado retenido sólo si I > IH'], [t('Circuito con carga resistiva y SCR ideal por estados. La histéresis depende del circuito y del pulso; no es una I–V intrínseca.', 'Resistively loaded circuit with ideal state-based SCR. Hysteresis depends on the circuit and trigger pulse; it is not intrinsic I–V.')]),
  device('cmos', 'circuits', 'Inversor CMOS', 'CMOS inverter', 'NOT', t('Transferencia lógica, corriente y ganancia.', 'Logic transfer, current and gain.'), t('Dos interruptores complementarios hacen que la salida cambie al estado opuesto de la entrada.', 'Two complementary switches make the output opposite to the input.'), [p('supply', 'Alimentación VDD', 'Supply VDD', 'V', 3.3, 1, 5, false, true), p('threshold', 'Umbral NMOS y |PMOS|', 'NMOS and |PMOS| threshold', 'V', .7, .1, 1.5), p('ratio', 'Relación βp/βn', 'Ratio βp/βn', '1', 1, .2, 5, false, true), p('beta', 'βn de conducción', 'Conduction βn', 'mA/V²', .5, .01, 10)], ['In(Vin, Vout) = Ip(VDD − Vin, VDD − Vout)', 'AV = dVout/dVin'], [compact, t('NMOS/PMOS de canal largo, λ = 0.02 V⁻¹, sin carga capacitiva ni simulación de retardos.', 'Long-channel NMOS/PMOS, λ = 0.02 V⁻¹, no capacitive load or delay simulation.')]),
  device('rc', 'circuits', 'Carga y filtro RC', 'RC charging and filter', 'RC', t('Transitorio, Bode y constante de tiempo.', 'Transient, Bode plot and time constant.'), t('El capacitor almacena carga y tarda en alcanzar la tensión de la fuente.', 'A capacitor stores charge and takes time to reach the source voltage.'), [resistor, capacitance, p('supply', 'Tensión del escalón', 'Step voltage', 'V', 5, .1, 20, false, true)], ['τ = RC', 'VC(t) = Vs[1 − exp(−t/RC)]', 'H(jω) = 1/(1 + jωRC)'], [t('Componentes lineales ideales y escalón de tensión; no incluye ESR, tolerancias dependientes de frecuencia ni ruido.', 'Ideal linear components and voltage step; no ESR, frequency-dependent tolerances or noise.')]),
  device('rlc', 'circuits', 'Resonador RLC serie', 'Series RLC resonator', 'RLC', t('Resonancia, fase y factor Q.', 'Resonance, phase and Q factor.'), [t('La energía pasa entre el campo eléctrico y el magnético; la resistencia amortigua la oscilación.', 'Energy moves between electric and magnetic fields; resistance damps oscillation.')][0], [{ ...resistor, default: 10 }, { ...capacitance, default: 10 }, p('inductance', 'Inductancia L', 'Inductance L', 'mH', 10, .001, 1000, true, true), p('supply', 'Amplitud de excitación', 'Excitation amplitude', 'V', 1, .01, 20)], ['f0 = 1/(2π√(LC))', 'Q = √(L/C)/R', '|I| = V/√[R² + (ωL − 1/(ωC))²]'], [t('RLC serie ideal de pequeña señal; no incluye saturación, parásitos ni pérdidas del núcleo.', 'Ideal small-signal series RLC; no saturation, parasitics or core losses.')]),
  device('rectifier', 'circuits', 'Puente rectificador', 'Bridge rectifier', 'AC/DC', t('Rectificación y filtrado de una señal senoidal.', 'Rectification and filtering of a sine wave.'), t('Cuatro diodos dirigen ambos semiciclos hacia una salida de la misma polaridad.', 'Four diodes steer both half-cycles into the same output polarity.'), [p('supply', 'Amplitud de entrada', 'Input amplitude', 'V', 10, 1, 50, false, true), p('frequency', 'Frecuencia de red', 'Line frequency', 'Hz', 60, 1, 1000), p('drop', 'Caída por diodo', 'Drop per diode', 'V', .7, .1, 1.5), { ...resistor, default: 1000 }, p('capacitance', 'Capacitor del filtro', 'Filter capacitor', 'µF', 100, .1, 1e4, true, true)], ['Vrect = max(|Vin| − 2Vd, 0)', 'VC(t + Δt) = max(Vrect, VC exp(−Δt/RC))'], [t('Diodos con caída constante y fuente ideal; descarga RC exacta entre muestras, sin corriente de irrupción ni resistencia de fuente.', 'Constant-drop diodes and ideal source; exact RC discharge between samples, no inrush current or source resistance.')]),
  device('recombination', 'foundations', 'Generación y recombinación', 'Generation and recombination', 'SRH', t('Vida media, SRH y longitud de difusión.', 'Lifetime, SRH and diffusion length.'), t('Las parejas creadas por luz pueden volver a desaparecer; la vida media mide qué tan rápido.', 'Light-generated pairs can disappear again; lifetime measures how quickly.'), [temperature, nd, tau, p('excess', 'Exceso inicial Δn = Δp', 'Initial excess Δn = Δp', 'cm⁻³', 1e14, 1e10, 1e18, true, true)], ['U = (np − ni²)/[τp(n + n1) + τn(p + p1)]', 'Δn(t) = Δn0 exp(−t/τ)', 'L = √(Dτ)'], [t('Trampa SRH a mitad de banda y τn = τp. El transitorio exponencial es el límite de baja inyección, separado de la curva SRH general.', 'Mid-gap SRH trap and τn = τp. Exponential transient is the low-injection limit, separate from the general SRH curve.')]),
  device('diffusion', 'fabrication', 'Difusión de dopantes', 'Dopant diffusion', 'D(t)', t('Predeposición y redistribución de dosis finita.', 'Predeposition and finite-dose drive-in.'), t('El calor permite que los dopantes se dispersen hacia el interior del material.', 'Heat lets dopants spread deeper into the material.'), [seconds, diffusionCoefficient, depth, p('surface', 'Concentración superficial Cs', 'Surface concentration Cs', 'cm⁻³', 1e19, 1e15, 1e21, true), p('dose', 'Dosis finita Q', 'Finite dose Q', 'cm⁻²', 1e14, 1e10, 1e17, true, true)], ['Cpre(x,t) = Cs erfc[x/(2√Dt)]', 'Cdrive(x,t) = Q exp[−x²/(4Dt)]/√(πDt)'], [t('Medio semiinfinito, D constante introducido para la temperatura elegida, sin solubilidad límite ni difusión dependiente de concentración.', 'Semi-infinite medium, constant user-supplied D at the chosen temperature, no solubility limit or concentration-dependent diffusion.')], ['fabrication', 'constants']),
  device('implantation', 'fabrication', 'Implantación y recocido', 'Implantation and anneal', 'Q/Rp', t('Perfil gaussiano y ensanchamiento por recocido.', 'Gaussian profile and annealing broadening.'), t('Los iones entran a cierta profundidad y se distribuyen alrededor de ella; el recocido ensancha el perfil.', 'Ions enter to a certain depth and spread around it; annealing broadens the profile.'), [p('dose', 'Dosis de implantación', 'Implant dose', 'cm⁻²', 1e14, 1e10, 1e17, true, true), p('range', 'Alcance proyectado Rp', 'Projected range Rp', 'µm', .3, .02, 5, false, true), p('straggle', 'Dispersión ΔRp', 'Straggle ΔRp', 'µm', .08, .005, 2), seconds, diffusionCoefficient, depth], ['C(x) = Q exp[−(x − Rp)²/(2σ²)]/(√(2π)σ)', 'σanneal² = σimplant² + 2Dt'], [t('Distribución gaussiana en línea infinita; se muestra x ≥ 0 y se reporta la fracción dentro del sustrato. No calcula canalización, daños ni activación.', 'Infinite-line Gaussian; x ≥ 0 is displayed and substrate dose fraction is reported. Does not calculate channeling, damage or activation.')], ['fabrication', 'constants']),
  device('oxidation', 'fabrication', 'Oxidación térmica', 'Thermal oxidation', 'SiO₂', t('Deal–Grove y consumo de silicio.', 'Deal–Grove and silicon consumption.'), t('El óxido crece mientras el oxidante atraviesa la capa que ya se ha formado.', 'Oxide grows while oxidant passes through the layer already formed.'), [p('time', 'Tiempo de oxidación', 'Oxidation time', 'min', 120, 1, 1000, false, true), p('linear', 'Constante A de proceso', 'Process constant A', 'µm', .1, .001, 2), p('parabolic', 'Constante B de proceso', 'Process constant B', 'µm²/min', .001, 1e-6, .1, true, true), p('initial', 'Óxido inicial', 'Initial oxide', 'nm', 10, 0, 1000)], ['x² + Ax = B(t + τ)', 'τ = (x0² + A x0)/B', 'Si consumido ≈ 0.44 xox'], [t('A y B son constantes ilustrativas editables para un proceso y temperatura fijos. Deal–Grove no describe correctamente el régimen ultradelgado.', 'A and B are editable illustrative constants for a fixed process and temperature. Deal–Grove does not accurately describe the ultrathin regime.')], ['oxidation', 'fabrication']),
  device('lithography', 'fabrication', 'Fotolitografía óptica', 'Optical photolithography', 'λ/NA', t('Resolución, foco y ventana de proceso.', 'Resolution, focus and process window.'), t('La luz copia un patrón, pero las estructuras pequeñas requieren controlar resolución y enfoque.', 'Light copies a pattern, but small structures require control of resolution and focus.'), [p('wavelength', 'Longitud de onda de exposición', 'Exposure wavelength', 'nm', 193, 13.5, 436, false, true), p('numerical_aperture', 'Apertura numérica NA', 'Numerical aperture NA', '1', .85, .1, 1.35, false, true), p('k1', 'Factor de proceso k1', 'Process factor k1', '1', .5, .25, 1), p('k2', 'Factor de foco k2', 'Focus factor k2', '1', .5, .2, 1), p('pitch', 'Paso del patrón', 'Pattern pitch', 'nm', 400, 40, 2000), p('contrast', 'Contraste de imagen supuesto', 'Assumed image contrast', '1', .8, .05, 1)], ['CDmin = k1 λ/NA', 'DOF = k2 λ/NA²', 'I(x) = 1 + m cos(2πx/pitch)'], [t('Criterios de Rayleigh e imagen sinusoidal ilustrativa. No es un solver electromagnético ni un modelo de resist o EUV multicapas.', 'Rayleigh criteria and illustrative sinusoidal image. Not an electromagnetic solver, resist model or EUV multilayer model.')], ['fabrication']),
  device('etching', 'fabrication', 'Grabado y selectividad', 'Etching and selectivity', 'ETCH', t('Consumo de máscara, profundidad y socavado.', 'Mask consumption, depth and undercut.'), t('Se elimina material por las ventanas de la máscara; la selectividad protege otras capas.', 'Material is removed through mask openings; selectivity protects other layers.'), [p('time', 'Tiempo de grabado', 'Etch time', 'min', 5, .1, 100, false, true), p('rate', 'Velocidad vertical', 'Vertical etch rate', 'nm/min', 100, 1, 5000, true), p('mask', 'Espesor de máscara', 'Mask thickness', 'nm', 200, 1, 5000), p('selectivity', 'Selectividad material/máscara', 'Material/mask selectivity', '1', 10, 1, 1000, true, true), p('anisotropy', 'Fracción lateral/vertical', 'Lateral/vertical fraction', '1', .1, 0, 1, false, true)], ['d = rate · t', 'Máscara consumida = d/selectivity', 'Socavado = anisotropy · d'], [t('Velocidades constantes hasta agotar la máscara; no incluye microcarga, plasma, facetas ni transporte de reactivos.', 'Constant rates until mask exhaustion; no microloading, plasma, facets or reactant transport.')], ['fabrication']),
  device('deposition', 'fabrication', 'Depósito de películas', 'Thin-film deposition', 'FILM', t('Crecimiento, resistencia de hoja y uniformidad.', 'Growth, sheet resistance and uniformity.'), t('Una película añade una capa aislante o conductora; su espesor cambia las propiedades eléctricas.', 'A film adds an insulating or conductive layer; thickness changes electrical properties.'), [p('time', 'Tiempo de depósito', 'Deposition time', 'min', 10, .1, 1000, false, true), p('rate', 'Velocidad de crecimiento', 'Growth rate', 'nm/min', 20, .1, 1000, true), p('resistivity', 'Resistividad de película', 'Film resistivity', 'µΩ·cm', 2.7, 1, 1e6, true), p('uniformity', 'Variación radial de espesor', 'Radial thickness variation', '%', 5, 0, 50, false, true)], ['h = rate · t', 'Rs = ρ/h', 'h(r) = h0[1 − u(r/R)²]'], [t('Crecimiento lineal y perfil radial prescrito; no simula cinética CVD/ALD, percolación ni efectos de tamaño.', 'Linear growth and prescribed radial profile; no CVD/ALD kinetics, percolation or size effects.')], ['fabrication']),
  device('yield', 'fabrication', 'Defectos y rendimiento', 'Defects and yield', 'YIELD', t('Área del chip y rendimiento Poisson/agrupado.', 'Die area and Poisson/clustered yield.'), t('Cuanto mayor es el chip, más oportunidades hay de que un defecto lo afecte.', 'The larger the chip, the more opportunities a defect has to affect it.'), [p('die_area', 'Área máxima de chip', 'Maximum die area', 'mm²', 100, 1, 1000, false, true), p('defects', 'Densidad de defectos letales', 'Killer defect density', 'cm⁻²', .5, .001, 10, true, true), p('clustering', 'Parámetro de agrupamiento α', 'Clustering parameter α', '1', 3, .1, 100)], ['YPoisson = exp(−D0 A)', 'Ycluster = (1 + D0 A/α)^(−α)'], [t('Probabilidad de sobrevivir a defectos letales; no incluye pérdidas paramétricas, sistemáticas, de prueba ni de encapsulado.', 'Probability of surviving killer defects; excludes parametric, systematic, test and packaging losses.')], ['fabrication']),
]

export function getDevice(id: DeviceId): Device {
  const found = DEVICES.find(device => device.id === id)
  if (!found) throw new Error(`Unknown device: ${id}`)
  return found
}
export function defaultConfig(id: DeviceId): Config { return { device: id, parameters: Object.fromEntries(getDevice(id).parameters.map(x => [x.key, x.default])), points: 201 } }

const baseGuide = (d: Device): Guide => ({
  id: `${d.id}-baseline`, device: d.id, title: t(`Primer experimento · ${d.name.es}`, `First experiment · ${d.name.en}`), level: 0,
  question: d.summary, hypothesis: d.story, parameters: {}, series: '',
  steps: [t('Prediga qué ocurrirá antes de ejecutar. Escriba su hipótesis en el cuaderno.', 'Predict what will happen before running. Write your hypothesis in the notebook.'), t('Ejecute con los valores iniciales y lea las unidades de cada eje.', 'Run with the initial values and read each axis unit.'), t(`Cambie sólo ${d.parameters.find(x => x.intro)?.label.es.toLowerCase() ?? 'un parámetro'} y compare con la referencia guardada.`, `Change only ${d.parameters.find(x => x.intro)?.label.en.toLowerCase() ?? 'one parameter'} and compare with the saved reference.`), t('Revise las otras curvas, anote lo observado y exporte el experimento.', 'Review the other curves, record observations and export the experiment.')],
  expected: t('La explicación de cada curva indica qué relación observar. Distinga los datos calculados de la animación conceptual.', 'Each curve explanation describes the relationship to observe. Distinguish calculated data from conceptual animation.'),
})
const guide = (id: string, device: DeviceId, level: number, title: Text, question: Text, hypothesis: Text, parameters: Record<string, number>, series: string, expected: Text): Guide => ({ id, device, level, title, question, hypothesis, parameters, series, expected, steps: [t('Guarde una referencia con los parámetros propuestos.', 'Save a reference using the proposed parameters.'), t('Identifique la variable independiente; mantenga constantes las demás.', 'Identify the independent variable; hold the others fixed.'), t('Ejecute tres valores o un barrido paramétrico y compare las curvas.', 'Run three values or a parameter sweep and compare curves.'), t('Cuantifique el cambio con unidades, exporte CSV/JSON y discuta los límites del modelo.', 'Quantify the change with units, export CSV/JSON and discuss model limitations.')] })
export const GUIDES: Guide[] = [
  ...DEVICES.map(baseGuide),
  guide('mass-action', 'material', 1, t('¿Dónde están los electrones y huecos?', 'Where are electrons and holes?'), t('¿Por qué aumentar electrones reduce huecos en equilibrio?', 'Why do more electrons reduce holes in equilibrium?'), t('En equilibrio np permanece igual a ni².', 'At equilibrium np stays equal to ni².'), { nd: 1e17, na: 1e13 }, 'electrons', t('Compruebe np/ni² = 1 y compare el efecto de la temperatura.', 'Check np/ni² = 1 and compare the effect of temperature.')),
  guide('einstein', 'transport', 3, t('Relación de Einstein', 'Einstein relation'), t('¿Cómo conecta difusión y movilidad?', 'How does diffusion connect to mobility?'), t('Dn/μn = VT y VT aumenta proporcionalmente a T.', 'Dn/μn = VT and VT is proportional to T.'), {}, 'drift', t('En 300 K, VT ≈ 25.85 mV. Distinga corriente de movimiento de electrones.', 'At 300 K, VT ≈ 25.85 mV. Distinguish current from electron motion.')),
  guide('pn-depletion', 'pn', 1, t('Abrir y cerrar la barrera', 'Opening and closing the barrier'), t('¿Qué hace la polarización inversa?', 'What does reverse bias do?'), t('La región de agotamiento crece en inversa.', 'The depletion region grows in reverse bias.'), { bias: -2 }, 'electric_field', t('Compare W(−2 V) con W(0 V); la corriente ideal inversa permanece próxima a −Is.', 'Compare W(−2 V) with W(0 V); ideal reverse current stays close to −Is.')),
  guide('pn-asymmetry', 'pn', 2, t('Dopaje asimétrico y neutralidad', 'Asymmetric doping and neutrality'), t('¿Qué lado se agota más?', 'Which side depletes more?'), t('NA xp = ND xn: el lado menos dopado se agota más.', 'NA xp = ND xn: the less doped side depletes more.'), { na: 1e17, nd: 1e15 }, 'charge_density', t('Las cargas integradas tienen igual magnitud y signos opuestos.', 'Integrated charges have equal magnitude and opposite signs.')),
  guide('diode-fit', 'pn', 4, t('Extraer idealidad de una medición I–V', 'Extract ideality from an I–V measurement'), t('¿Coincide una medición con Shockley en baja inyección?', 'Does a measurement follow low-injection Shockley behavior?'), t('La pendiente de ln(I) vs V es 1/(n VT).', 'The slope of ln(I) vs V is 1/(n VT).'), { start: .15, stop: .5 }, 'iv', t('Importe CSV en V y A. Seleccione la zona exponencial; compare n, Is y residuos sin asumir calibración.', 'Import CSV in V and A. Select the exponential region; compare n, Is and residuals without assuming calibration.')),
  guide('pin-width', 'pin', 2, t('Velocidad frente a capacitancia', 'Speed versus capacitance'), t('¿Una región I más ancha siempre mejora un detector?', 'Does a wider I region always improve a detector?'), t('Una I más ancha reduce C pero alarga el tránsito.', 'A wider I region lowers C but increases transit time.'), {}, 'capacitance', t('Compare espesor, capacitancia y tránsito; no confunda tránsito con ancho de banda total.', 'Compare thickness, capacitance and transit; do not confuse transit with total bandwidth.')),
  guide('zener-power', 'zener', 2, t('Regulación y disipación', 'Regulation and dissipation'), t('¿Por qué la regulación exige limitar corriente?', 'Why does regulation require current limiting?'), t('En ruptura aumenta |I| y también la potencia disipada.', 'In breakdown |I| and dissipated power increase.'), {}, 'power', t('Lea P = |VI|. El modelo no establece límites térmicos seguros del componente.', 'Read P = |VI|. The model does not establish safe component thermal limits.')),
  guide('schottky-temperature', 'schottky', 3, t('Barrera y temperatura', 'Barrier and temperature'), t('¿Cómo cambia Is con la temperatura?', 'How does Is change with temperature?'), t('La emisión termoiónica contiene T² exp(−ΦB/VT).', 'Thermionic emission contains T² exp(−ΦB/VT).'), {}, 'iv', t('Barra T y ΦB por separado; documente A* y el área usados.', 'Sweep T and ΦB separately; document A* and the area used.')),
  guide('cv-extraction', 'varactor', 4, t('Extraer dopaje con C–V', 'Extract doping using C–V'), t('¿Es lineal 1/C² en una unión abrupta?', 'Is 1/C² linear for an abrupt junction?'), t('La pendiente es proporcional a (1/NA + 1/ND)/A².', 'The slope is proportional to (1/NA + 1/ND)/A².'), {}, 'inverse_capacitance', t('Use área en cm² y capacitancia en F para extraer dopaje equivalente; el eje usa pF⁻².', 'Use area in cm² and capacitance in F to extract effective doping; the axis uses pF⁻².')),
  guide('negative-resistance', 'tunnel', 3, t('Resistencia diferencial negativa', 'Negative differential resistance'), t('¿Dónde es dI/dV < 0?', 'Where is dI/dV < 0?'), t('Después del pico aparece una rama descendente.', 'A descending branch follows the peak.'), {}, 'conductance', t('Localice el intervalo de conductancia negativa y explique por qué este modelo no demuestra túnel cuántico.', 'Locate the negative-conductance interval and explain why this model does not demonstrate quantum tunneling.')),
  guide('led-photons', 'led', 1, t('El color y la energía de la luz', 'Light color and energy'), t('¿Por qué el azul requiere fotones de más energía?', 'Why does blue light require higher-energy photons?'), t('λ disminuye al aumentar la energía del fotón.', 'Wavelength decreases as photon energy increases.'), { bandgap: 2.7 }, 'optical_power', t('Compare 1.9 eV y 2.7 eV. La animación muestra eventos, no un espectro medido.', 'Compare 1.9 eV and 2.7 eV. Animation shows events, not a measured spectrum.')),
  guide('photo-responsivity', 'photodiode', 2, t('Medir luz con corriente', 'Measure light using current'), t('¿Se duplica Iph al duplicar potencia?', 'Does doubling power double Iph?'), t('Con EQE y λ fijas, Iph es proporcional a P.', 'With fixed EQE and wavelength, Iph is proportional to P.'), {}, 'iv', t('Compare oscuridad y luz; revise responsividad A/W y límite RC.', 'Compare dark and illuminated response; review A/W responsivity and the RC limit.')),
  guide('solar-mpp', 'solar', 2, t('Buscar la máxima potencia', 'Find maximum power'), t('¿El máximo de potencia coincide con Voc?', 'Does maximum power occur at Voc?'), t('En Voc no hay corriente; MPP está dentro de la curva.', 'At Voc there is no current; MPP lies inside the curve.'), {}, 'power', t('Lea Vmpp, Impp, FF y eficiencia; documente Pin para que la eficiencia tenga sentido.', 'Read Vmpp, Impp, FF and efficiency; document Pin for a meaningful efficiency.')),
  guide('bjt-regions', 'npn', 2, t('Activa y saturación del BJT', 'BJT active region and saturation'), t('¿Cuándo deja de ser útil IC ≈ βIB?', 'When does IC ≈ βIB stop being useful?'), t('En saturación la unión base–colector también conduce.', 'In saturation the base–collector junction also conducts.'), {}, 'collector', t('Compare IC e IB a bajo y alto VCE; compruebe KCL en todas las regiones.', 'Compare IC and IB at low and high VCE; check KCL in every region.')),
  guide('pnp-signs', 'pnp', 2, t('Convenciones de signo PNP', 'PNP sign conventions'), t('¿Qué cambia al invertir el tipo del transistor?', 'What changes when transistor type is reversed?'), t('Las magnitudes se conservan y los signos de corriente/tensión cambian.', 'Magnitudes are preserved and voltage/current signs reverse.'), {}, 'collector', t('Compare un NPN con el mismo β e Is; use corriente entrante al terminal como positiva.', 'Compare an NPN with the same β and Is; terminal-entering current is positive.')),
  guide('mos-gm', 'nmos', 3, t('Extraer gm y umbral', 'Extract gm and threshold'), t('¿Cómo cambia gm con la sobreexcitación de puerta?', 'How does gm change with gate overdrive?'), t('En saturación de canal largo gm crece con VGS − Vth.', 'Long-channel saturation gm increases with VGS − Vth.'), {}, 'gm', t('Compare gm, transferencia y salida. Mantenga VDS fijo y documente W/L y Cox.', 'Compare gm, transfer and output. Hold VDS fixed and document W/L and Cox.')),
  guide('moscap-regimes', 'moscap', 3, t('C–V de baja y alta frecuencia', 'Low- and high-frequency C–V'), t('¿Por qué difieren las curvas en inversión?', 'Why do curves differ in inversion?'), t('Las cargas minoritarias pueden seguir la señal lenta, pero no la rápida.', 'Minority carriers can follow a slow signal but not a fast one.'), {}, 'capacitance_lf', t('La curva HF usa agotamiento máximo; no se calcula una frecuencia ni trampas de interfaz.', 'HF uses maximum depletion; no explicit frequency or interface traps are calculated.')),
  guide('jfet-pinch', 'jfet', 2, t('Pinzar un canal sin puerta aislada', 'Pinch a channel without an insulated gate'), t('¿Qué hace VGS más negativo?', 'What does a more negative VGS do?'), t('Disminuye la corriente hasta el corte en VGS = Vp.', 'Current decreases until cutoff at VGS = Vp.'), {}, 'transfer', t('Identifique corte, zona óhmica y saturación.', 'Identify cutoff, ohmic and saturation regions.')),
  guide('cmos-switch', 'cmos', 2, t('Equilibrar un inversor', 'Balance an inverter'), t('¿Cómo mueve βp/βn el punto de conmutación?', 'How does βp/βn move the switching point?'), t('Un PMOS más fuerte desplaza la transición de entrada.', 'A stronger PMOS moves the input transition.'), {}, 'transfer', t('Compare ratios 0.5, 1 y 2; revise la corriente estática durante la transición.', 'Compare ratios 0.5, 1 and 2; review static current during transition.')),
  guide('rc-time', 'rc', 1, t('¿Qué significa una constante de tiempo?', 'What does a time constant mean?'), t('¿Cuánto se carga en t = RC?', 'How much charge is reached at t = RC?'), t('VC alcanza aproximadamente 63.2% del escalón.', 'VC reaches approximately 63.2% of the step.'), {}, 'charging', t('Compruebe el tiempo y conecte τ con fc = 1/(2πRC).', 'Check time and connect τ to fc = 1/(2πRC).')),
  guide('rlc-quality', 'rlc', 3, t('Resonancia y factor Q', 'Resonance and Q factor'), t('¿Qué hace aumentar la resistencia?', 'What does increasing resistance do?'), t('Reduce Q y la corriente resonante sin cambiar f0 ideal.', 'It lowers Q and resonant current without changing ideal f0.'), {}, 'current', t('Compare ancho de resonancia y fase; identifique el circuito serie.', 'Compare resonance width and phase; identify the series circuit.')),
  guide('rectifier-ripple', 'rectifier', 2, t('Reducir el rizado', 'Reduce ripple'), t('¿Cómo cambia el rizado con C y carga?', 'How does ripple change with C and load?'), t('Más C o menos corriente de carga reducen el rizado.', 'More C or less load current reduces ripple.'), {}, 'filtered', t('Lea el rizado del último período, después del arranque; compare refinamiento temporal.', 'Read ripple in the last period after startup; compare time refinement.')),
  guide('lifetime', 'recombination', 3, t('Estimar vida media', 'Estimate carrier lifetime'), t('¿Cuándo es válida una caída exponencial?', 'When is exponential decay valid?'), t('En baja inyección el exceso cae a 1/e en una vida media.', 'At low injection the excess falls to 1/e in one lifetime.'), {}, 'decay', t('Compare Δn/ND; si no es pequeño, use SRH general y discuta la limitación del transitorio.', 'Compare Δn/ND; when it is not small, use general SRH and discuss the transient limitation.')),
  guide('diffusion-dose', 'diffusion', 4, t('Conservar dosis en redistribución', 'Conserve dose during drive-in'), t('¿La integral del perfil coincide con la dosis?', 'Does the profile integral match the dose?'), t('La redistribución ensancha el perfil conservando Q en el medio semiinfinito.', 'Drive-in broadens the profile while preserving Q in the semi-infinite medium.'), {}, 'drive_in', t('Aumente profundidad y muestreo. Una ventana corta pierde dosis visible, no dosis física.', 'Increase depth and sampling. A short window loses visible dose, not physical dose.')),
  guide('anneal-variance', 'implantation', 3, t('Recocido y dispersión', 'Annealing and spread'), t('¿Cómo cambia σ² con tiempo?', 'How does variance change with time?'), t('σ² crece en 2Dt para D constante.', 'Variance increases by 2Dt at constant D.'), {}, 'annealed', t('Reporte la fracción gaussiana en x ≥ 0; no interprete una gaussiana como activación eléctrica.', 'Report Gaussian fraction at x ≥ 0; do not equate Gaussian concentration with electrical activation.')),
  guide('oxide-regimes', 'oxidation', 3, t('Régimen lineal y parabólico', 'Linear and parabolic regimes'), t('¿Por qué el crecimiento se vuelve más lento?', 'Why does growth slow down?'), t('En óxido grueso domina la difusión a través de la capa.', 'Diffusion through the layer dominates for thick oxide.'), {}, 'oxide', t('Compare x frente a t y x² + Ax frente a t; use constantes A/B de un proceso documentado.', 'Compare x versus t and x² + Ax versus t; use A/B constants from a documented process.')),
  guide('resolution-focus', 'lithography', 2, t('Resolución contra profundidad de foco', 'Resolution versus depth of focus'), t('¿Qué sacrifica una NA mayor?', 'What does a higher NA sacrifice?'), t('Mejora resolución pero reduce DOF.', 'It improves resolution but reduces DOF.'), {}, 'resolution', t('Compare CDmin y DOF como funciones de NA; la imagen sinusoidal es conceptual.', 'Compare CDmin and DOF versus NA; the sinusoidal image is conceptual.')),
  guide('etch-mask', 'etching', 2, t('¿Sobrevive la máscara?', 'Does the mask survive?'), t('¿Cuándo se pierde la protección?', 'When is protection lost?'), t('La máscara se consume a rate/selectivity.', 'The mask is consumed at rate/selectivity.'), {}, 'mask', t('El modelo detiene el grabado protegido al agotarse la máscara; compare selectividad y socavado.', 'The protected etch model stops at mask exhaustion; compare selectivity and undercut.')),
  guide('sheet-resistance', 'deposition', 3, t('Resistencia de hoja y uniformidad', 'Sheet resistance and uniformity'), t('¿Qué región de la oblea tiene mayor Rs?', 'Which wafer region has higher sheet resistance?'), t('La región más delgada tiene mayor Rs.', 'The thinner region has higher sheet resistance.'), {}, 'sheet_radial', t('Reporte nm, µΩ·cm y Ω/□; identifique qué perfil radial se ha supuesto.', 'Report nm, µΩ·cm and Ω/□; identify the assumed radial profile.')),
  guide('yield-area', 'yield', 2, t('Tamaño, defectos y rendimiento', 'Size, defects and yield'), t('¿Por qué fabricar un chip grande cuesta más?', 'Why does a large chip cost more to manufacture?'), t('Aumentar área reduce la probabilidad de no encontrar defectos letales.', 'Larger area lowers the probability of avoiding killer defects.'), {}, 'poisson', t('Convierta mm² a cm² antes de usar D0; compare Poisson y agrupamiento.', 'Convert mm² to cm² before using D0; compare Poisson and clustering.')),
]
