import { useEffect, useMemo, useRef, useState } from 'react'
import type { Mode } from '../types'
import type { PlotOverlay } from '../Plot'
import { CATEGORIES, DEVICES, GUIDES, REFERENCES, defaultConfig, getDevice } from './catalogue'
import CarrierAnimation from './CarrierAnimation'
import FabricationFlow from './FabricationFlow'
import LocalTCAD from './LocalTCAD'
import LabPlot, { Histogram, number } from './LabPlot'
import { compareMeasurement, diodeFit, downloadFile, linearFit, parseMeasurement, reproducibilityBundle, seriesCsv, statistics, type Fit, type Measurement } from './scientific'
import { text as t, type Category, type Config, type DeviceId, type Guide, type LabSeries, type Locale, type Parameter, type Result, type Study, type StudyRequest, type WorkerReply } from './types'
import './lab.css'

const MODES: Mode[] = ['Explore', 'Learn', 'Design', 'Advanced', 'Research']
const COLORS = ['#75bcf1', '#e9c577', '#eea2d3', '#b6a0ed', '#eb9790', '#9cd48c', '#88c9c0', '#c9a083']
type Notebook = { hypothesis: string; observations: string; conclusion: string; complete: boolean }
const emptyNotebook = (): Notebook => ({ hypothesis: '', observations: '', conclusion: '', complete: false })
const parameterText = (value: number) => Math.abs(value) >= 1e5 || value !== 0 && Math.abs(value) < .001 ? value.toExponential() : String(value)
function readNotebook(id: string): Notebook {
  try { const value = JSON.parse(localStorage.getItem(`opensemilab.lab-notebook.${id}`) ?? '{}'); return { hypothesis: typeof value.hypothesis === 'string' ? value.hypothesis.slice(0, 20000) : '', observations: typeof value.observations === 'string' ? value.observations.slice(0, 20000) : '', conclusion: typeof value.conclusion === 'string' ? value.conclusion.slice(0, 20000) : '', complete: value.complete === true } } catch { return emptyNotebook() }
}
function ParameterField({ spec, value, locale, onChange, onValidity }: { spec: Parameter; value: number; locale: Locale; onChange: (value: number) => void; onValidity: (invalid: boolean) => void }) {
  const [draft, setDraft] = useState(parameterText(value)), [invalid, setInvalid] = useState(false)
  useEffect(() => { setDraft(parameterText(value)); setInvalid(false); onValidity(false) }, [value])
  const invalidDraft = (raw: string) => { const parsed = Number(raw); return !raw.trim() || !Number.isFinite(parsed) || parsed < spec.min || parsed > spec.max || !!spec.integer && !Number.isInteger(parsed) }
  const commit = () => { const bad = invalidDraft(draft); setInvalid(bad); onValidity(bad); if (!bad) onChange(Number(draft)) }
  const rangeValue = spec.log ? Math.log10(Math.max(spec.min, value)) : value
  return <label className={`dl-field ${invalid ? 'invalid' : ''}`}><span>{spec.label[locale]}</span><div><input aria-label={spec.label[locale]} aria-invalid={invalid} type="text" inputMode="decimal" value={draft} onChange={event => { const raw = event.target.value; setDraft(raw); const bad = invalidDraft(raw); setInvalid(bad); onValidity(bad) }} onBlur={commit} onKeyDown={event => { if (event.key === 'Enter') { commit(); event.currentTarget.blur() } }}/><b>{spec.unit}</b></div>
    {spec.intro && <input aria-label={`${spec.label[locale]} ${locale === 'es' ? 'deslizador' : 'slider'}`} type="range" min={spec.log ? Math.log10(spec.min) : spec.min} max={spec.log ? Math.log10(spec.max) : spec.max} step="any" value={rangeValue} onChange={event => { const raw = Number(event.target.value); onChange(Number((spec.log ? 10 ** raw : raw).toPrecision(5))) }}/>}<small>{invalid ? (locale === 'es' ? 'Revise el rango: ' : 'Check range: ') : ''}{number(spec.min)} — {number(spec.max)} {spec.unit}</small></label>
}

export default function DeviceLaboratory({ locale, mode }: { locale: Locale; mode: Mode }) {
  const es = locale === 'es', level = MODES.indexOf(mode)
  const [config, setConfig] = useState<Config>(() => defaultConfig('pn')), [result, setResult] = useState<Result | null>(null), [reference, setReference] = useState<Result | null>(null)
  const [active, setActive] = useState('potential'), [category, setCategory] = useState<Category | 'all'>('all'), [search, setSearch] = useState(''), [busy, setBusy] = useState(''), [error, setError] = useState('')
  const [guideId, setGuideId] = useState('pn-baseline'), [guideSearch, setGuideSearch] = useState(''), [notebook, setNotebook] = useState<Notebook>(() => readNotebook('pn-baseline')), [storageError, setStorageError] = useState(false)
  const [study, setStudy] = useState<Study | null>(null), [studyParameter, setStudyParameter] = useState('na'), [variation, setVariation] = useState(8), [seed, setSeed] = useState(2026), [samples, setSamples] = useState(20), [statMetric, setStatMetric] = useState('vbi')
  const [measurement, setMeasurement] = useState<{ data: Measurement; filename: string; device: DeviceId; series: string } | null>(null), [measurementError, setMeasurementError] = useState(''), [unitsConfirmed, setUnitsConfirmed] = useState(false)
  const [invalidFields, setInvalidFields] = useState<string[]>([]), [parameterVersion, setParameterVersion] = useState(0)
  const [fit, setFit] = useState<(Fit & { ideality?: number; isat?: number }) | null>(null), [fitStart, setFitStart] = useState(.2), [fitStop, setFitStop] = useState(.5), [tcadOpen, setTcadOpen] = useState(false)
  const worker = useRef<Worker | null>(null), requestId = useRef(0), bench = useRef<HTMLElement>(null)
  const device = getDevice(config.device), guide = GUIDES.find(g => g.id === guideId) ?? GUIDES.find(g => g.device === config.device)!
  const dirty = !!result && (config.device !== result.config.device || config.points !== result.config.points || device.parameters.some(p => config.parameters[p.key] !== result.config.parameters[p.key]))
  const selected = result?.series.find(s => s.name === active) ?? result?.series[0]
  const devices = DEVICES.filter(d => (category === 'all' || d.category === category) && `${d.name.es} ${d.name.en} ${d.summary[locale]} ${d.symbol}`.toLowerCase().includes(search.toLowerCase()))
  const guides = GUIDES.filter(g => (!guideSearch || `${g.title.es} ${g.title.en} ${g.question[locale]}`.toLowerCase().includes(guideSearch.toLowerCase())) && g.level <= level)
  const visibleMeasurement = measurement?.device === config.device && measurement.series === selected?.name ? measurement : null
  const comparison = useMemo(() => { try { return visibleMeasurement && selected ? compareMeasurement(visibleMeasurement.data, selected) : null } catch { return null } }, [visibleMeasurement, selected])

  function run(next: Config = config, request?: StudyRequest, preferredSeries?: string) {
    worker.current?.terminate(); const id = ++requestId.current
    setError(''); setBusy(request ? request.type : 'run')
    try {
      const job = new Worker(new URL('./worker.ts', import.meta.url), { type: 'module' }); worker.current = job
      job.onmessage = ({ data }: MessageEvent<WorkerReply>) => {
        if (data.id !== requestId.current) return
        setBusy(''); job.terminate(); worker.current = null
        if (data.error) { setError(data.error); return }
        if (data.result) { const value = data.result; setResult(value); setStudy(null); setFit(null); setActive(current => preferredSeries && value.series.some(s => s.name === preferredSeries) ? preferredSeries : value.series.some(s => s.name === current) ? current : value.series[0].name); setStatMetric(current => value.metrics.some(m => m.id === current) ? current : value.metrics[0].id) }
        if (data.study) setStudy(data.study)
      }
      job.onerror = event => { if (id !== requestId.current) return; setError(event.message || (es ? 'Falló el cálculo del cliente.' : 'Client calculation failed.')); setBusy(''); job.terminate(); worker.current = null }
      job.postMessage({ id, config: next, study: request })
    } catch (reason) { setBusy(''); setError(reason instanceof Error ? reason.message : String(reason)) }
  }
  useEffect(() => { run(defaultConfig('pn')); return () => { ++requestId.current; worker.current?.terminate() } }, [])
  useEffect(() => { try { localStorage.setItem(`opensemilab.lab-notebook.${guideId}`, JSON.stringify({ ...notebook, updated_at: new Date().toISOString() })); setStorageError(false) } catch { setStorageError(true) } }, [notebook, guideId])
  useEffect(() => { setUnitsConfirmed(false); setFit(null) }, [selected?.name, config.device])
  function chooseGuide(next: Guide) {
    const cfg = defaultConfig(next.device); cfg.parameters = { ...cfg.parameters, ...next.parameters }
    setConfig(cfg); setGuideId(next.id); const saved = readNotebook(next.id); setNotebook(saved.hypothesis ? saved : { ...saved, hypothesis: next.hypothesis[locale] })
    setReference(null); setStudy(null); setMeasurement(null); setTcadOpen(false); setInvalidFields([]); setParameterVersion(value => value + 1); setMeasurementError(''); setStudyParameter(getDevice(next.device).parameters.find(p => p.intro && p.default !== 0)?.key ?? getDevice(next.device).parameters[0].key)
    setActive(next.series); setResult(null); run(cfg, undefined, next.series)
  }
  const chooseDevice = (id: DeviceId) => chooseGuide(GUIDES.find(g => g.device === id)!)
  const scrollToBench = () => bench.current?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' })
  const reportValidity = (key: string, bad: boolean) => setInvalidFields(current => bad ? current.includes(key) ? current : [...current, key] : current.includes(key) ? current.filter(k => k !== key) : current)
  function cancel() { ++requestId.current; worker.current?.terminate(); worker.current = null; setBusy('') }
  function updateParameter(key: string, value: number) { setConfig(current => ({ ...current, parameters: { ...current.parameters, [key]: value } })) }
  async function exportBundle() {
    if (!result) return
    try { const bundle = await reproducibilityBundle(result, { guide: guide.id, ...notebook, measurement: visibleMeasurement, fit }, study); downloadFile(`${config.device}-experiment.json`, JSON.stringify(bundle, null, 2)) }
    catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)) }
  }
  async function importMeasurement(file: File) {
    setMeasurementError(''); setFit(null)
    try { if (!selected || !unitsConfirmed) throw new Error(es ? 'Confirme primero las unidades de la curva.' : 'Confirm curve units first.'); if (file.size > 2_000_000) throw new Error('CSV > 2 MB'); const data = parseMeasurement(await file.text()); compareMeasurement(data, selected); setMeasurement({ data, filename: file.name, device: config.device, series: selected.name }) }
    catch (reason) { setMeasurementError(reason instanceof Error ? reason.message : String(reason)) }
  }
  function fitMeasurement(diode = false) {
    if (!visibleMeasurement) return
    try {
      const data = visibleMeasurement.data, indices = data.x.flatMap((x, i) => x >= fitStart && x <= fitStop ? [i] : [])
      setFit(diode ? diodeFit(data, result?.config.parameters.temperature ?? 300, fitStart, fitStop) : linearFit(indices.map(i => data.x[i]), indices.map(i => data.y[i]), data.sigma ? indices.map(i => data.sigma![i]) : undefined)); setMeasurementError('')
    } catch (reason) { setMeasurementError(reason instanceof Error ? reason.message : String(reason)) }
  }
  const overlays: PlotOverlay[] = []
  if (selected) {
    const prior = reference?.series.find(s => s.name === selected.name && s.x_unit === selected.x_unit && s.y_unit === selected.y_unit)
    if (prior) overlays.push({ series: prior, color: '#e9c577', dashed: true, label: es ? 'Referencia guardada' : 'Saved reference' })
    if (selected.name === 'conduction_band') { const valence = result?.series.find(s => s.name === 'valence_band'); if (valence) overlays.push({ series: valence, color: '#eea2d3', label: 'Ev' }) }
    if (selected.name === 'capacitance_lf') { const hf = result?.series.find(s => s.name === 'capacitance_hf'); if (hf) overlays.push({ series: hf, color: '#75bcf1', label: 'HF' }) }
    if (selected.name === 'output' && ['nmos', 'pmos'].includes(config.device)) result?.series.filter(s => s.name.startsWith('output_')).forEach((s, i) => overlays.push({ series: s, color: COLORS[i], label: s.label[locale] }))
    if (selected.name === 'srh_decay') { const low = result?.series.find(s => s.name === 'decay'); if (low) overlays.push({ series: low, color: '#e9c577', dashed: true, label: es ? 'Límite baja inyección' : 'Low-injection limit' }) }
    if (selected.name === 'up') { const down = result?.series.find(s => s.name === 'down'); if (down) overlays.push({ series: down, color: '#75bcf1', label: es ? 'Rampa descendente' : 'Falling ramp' }) }
    study?.runs.slice(0, 8).forEach((run, i) => { const curve = run.result.series.find(s => s.name === selected.name); if (curve && curve.x_unit === selected.x_unit && curve.y_unit === selected.y_unit) overlays.push({ series: curve, color: COLORS[i], label: run.label }) })
    if (visibleMeasurement) { const data = visibleMeasurement.data, indices = data.x.flatMap((_, i) => i % Math.max(1, Math.ceil(data.x.length / 500)) === 0 ? [i] : []); overlays.push({ series: { ...selected, x: indices.map(i => data.x[i]), y: indices.map(i => data.y[i]) }, color: '#ffa0a0', label: es ? 'Medición importada' : 'Imported measurement', pointsOnly: true }) }
  }
  const studyMetric = result?.metrics.find(m => m.id === statMetric) ?? result?.metrics[0], values = study && studyMetric ? study.runs.map(r => r.result.metrics.find(m => m.id === studyMetric.id)!.value) : [], stats = values.length ? statistics(values) : null

  return <main className="device-laboratory">
    <section className="dl-hero"><div><p className="eyebrow">{es ? 'LABORATORIO DE DISPOSITIVOS Y FABRICACIÓN' : 'DEVICE AND FABRICATION LABORATORY'}</p><h1>{es ? 'Del electrón' : 'From the electron'}<br/><span>{es ? 'al chip.' : 'to the chip.'}</span></h1><p>{es ? 'Observe, formule una hipótesis y experimente. Conecte cada curva con la materia, el dispositivo y el proceso que la produce.' : 'Observe, form a hypothesis and experiment. Connect every curve to the material, device and process that produces it.'}</p></div><div className="dl-hero-facts"><b>{DEVICES.length}<span>{es ? 'dispositivos y módulos' : 'devices and modules'}</span></b><b>{GUIDES.length}<span>{es ? 'experimentos guiados' : 'guided experiments'}</span></b><p>{es ? 'Cálculo y animación en su equipo' : 'Calculation and animation on your computer'}</p></div></section>

    <section className="dl-catalogue" aria-label={es ? 'Catálogo de dispositivos' : 'Device catalogue'}><div className="dl-section-title"><div><span>01 · {es ? 'ELIJA QUÉ EXPLORAR' : 'CHOOSE WHAT TO EXPLORE'}</span><h2>{es ? 'Una biblioteca para experimentar' : 'A library for experimentation'}</h2></div><input type="search" aria-label={es ? 'Buscar dispositivo' : 'Search devices'} placeholder={es ? 'MOSFET, diodo, fabricación…' : 'MOSFET, diode, fabrication…'} value={search} onChange={event => setSearch(event.target.value)}/></div><div className="dl-categories"><button aria-pressed={category === 'all'} onClick={() => setCategory('all')}>{es ? 'Todos' : 'All'} ({DEVICES.length})</button>{Object.entries(CATEGORIES).map(([id, label]) => <button key={id} aria-pressed={category === id} onClick={() => setCategory(id as Category)}>{label[locale]}</button>)}</div><div className="dl-device-grid">{devices.map(d => <button key={d.id} aria-pressed={d.id === config.device} onClick={() => chooseDevice(d.id)} data-device={d.id}><span>{d.symbol}</span><b>{d.name[locale]}</b><small>{d.summary[locale]}</small></button>)}</div>{!devices.length && <p>{es ? 'No hay coincidencias.' : 'No matching devices.'}</p>}</section>

    <section ref={bench} className="dl-workspace" aria-label={es ? 'Banco de experimentos' : 'Experiment bench'}>
      <aside className="dl-controls"><div className="dl-section-title"><div><span>02 · {es ? 'CONFIGURE' : 'CONFIGURE'}</span><h2>{device.name[locale]}</h2></div><small>{device.symbol}</small></div><p className="dl-story">{level < 2 ? device.story[locale] : device.summary[locale]}</p><div className="dl-parameters">{device.parameters.filter(p => level >= 2 || p.intro).map(spec => <ParameterField key={`${config.device}-${spec.key}-${parameterVersion}`} spec={spec} value={config.parameters[spec.key]} locale={locale} onValidity={bad => reportValidity(spec.key, bad)} onChange={value => updateParameter(spec.key, value)}/>)}</div>
        {level < 2 && <details className="dl-extra-parameters"><summary>{es ? 'Ver todos los parámetros' : 'See all parameters'}</summary><div className="dl-parameters">{device.parameters.filter(p => !p.intro).map(spec => <ParameterField key={`${config.device}-${spec.key}-${parameterVersion}`} spec={spec} value={config.parameters[spec.key]} locale={locale} onValidity={bad => reportValidity(spec.key, bad)} onChange={value => updateParameter(spec.key, value)}/>)}</div></details>}
        <label className="dl-sampling">{es ? 'Muestreo para las curvas' : 'Curve sampling'}<select value={config.points} onChange={event => setConfig(current => ({ ...current, points: Number(event.target.value) }))}>{[101, 201, 501, 1001].map(value => <option key={value} value={value}>{value} {es ? 'puntos' : 'points'}</option>)}</select></label>
        <button className="run" onClick={() => run()} disabled={!!busy || invalidFields.length > 0}>{busy ? (es ? 'Calculando en su equipo…' : 'Calculating on your computer…') : (es ? 'Ejecutar experimento' : 'Run experiment')} <span>→</span></button>{busy && <button className="dl-cancel" onClick={cancel}>{es ? 'Cancelar cálculo' : 'Cancel calculation'}</button>}<button className="dl-reset" onClick={() => { const cfg = defaultConfig(config.device); setConfig(cfg); setInvalidFields([]); setParameterVersion(value => value + 1); run(cfg) }}>{es ? 'Restaurar parámetros iniciales' : 'Restore initial parameters'}</button>
        {error && <p className="error" role="alert">{error}</p>}{dirty && <p className="dl-notice" role="status">{es ? 'Parámetros modificados. Ejecute para actualizar las curvas; lo visible pertenece a la última ejecución.' : 'Parameters changed. Run to update curves; visible data belongs to the last run.'}</p>}<p className="dl-caption">{es ? 'Motor analítico / compacto · Web Worker en el cliente. Cada resultado conserva la configuración ejecutada.' : 'Analytic / compact engine · Web Worker on the client. Every result retains its executed configuration.'}</p>
      </aside>
      <div className="dl-results"><div className="dl-section-title"><div><span>03 · {es ? 'OBSERVE Y MIDA' : 'OBSERVE AND MEASURE'}</span><h2>{es ? 'Del fenómeno a los datos' : 'From phenomenon to data'}</h2></div><small data-testid="lab-status">{busy ? (es ? 'CALCULANDO' : 'CALCULATING') : result ? (es ? 'CALCULADO' : 'CALCULATED') : (es ? 'LISTO' : 'READY')}</small></div>
        <div className="dl-metrics">{result?.metrics.map(m => <div key={m.id}><span>{m.label[locale]}</span><b>{number(m.value)}</b><small>{m.unit}</small></div>)}</div><div className="dl-plot-tabs">{result?.series.map(s => <button key={s.name} aria-pressed={selected?.name === s.name} onClick={() => setActive(s.name)}>{s.label[locale]}</button>)}</div><LabPlot series={selected} overlays={overlays} locale={locale} result={result}/>
        <div className="dl-result-actions"><button disabled={!result || dirty} onClick={() => setReference(result)}>{es ? 'Guardar referencia' : 'Save reference'}</button>{reference && <button onClick={() => setReference(null)}>{es ? 'Quitar referencia' : 'Remove reference'}</button>}<button disabled={!selected} onClick={() => selected && downloadFile(`${config.device}-${selected.name}.csv`, seriesCsv(selected), 'text/csv;charset=utf-8')}>{es ? 'Exportar CSV de curva' : 'Export curve CSV'}</button><button disabled={!result} onClick={() => void exportBundle()}>{es ? 'Exportar experimento JSON' : 'Export experiment JSON'}</button></div>
        {result && <ul className="dl-warnings">{result.warnings.map((warning, i) => <li key={i}>{warning[locale]}</li>)}</ul>}
        {device.category !== 'fabrication' && device.category !== 'circuits' && !['cmos', 'scr', 'jfet'].includes(config.device) && result && <CarrierAnimation key={config.device} config={result.config} locale={locale}/>}
      </div>
    </section>

    <section className="dl-guide-panel"><div className="dl-section-title"><div><span>04 · {es ? 'APRENDA CON UN PROPÓSITO' : 'LEARN WITH A PURPOSE'}</span><h2>{guide.title[locale]}</h2></div><small>{es ? 'GUÍA DEL EXPERIMENTO' : 'EXPERIMENT GUIDE'}</small></div><div className="dl-guide-columns"><div><h3>{es ? 'Pregunta' : 'Question'}</h3><p>{guide.question[locale]}</p><h3>{es ? 'Hipótesis de referencia' : 'Reference hypothesis'}</h3><p>{guide.hypothesis[locale]}</p><h3>{es ? 'Qué observar' : 'What to observe'}</h3><p>{guide.expected[locale]}</p></div><ol>{guide.steps.map((step, i) => <li key={i}>{step[locale]}</li>)}</ol></div></section>

    <section className="dl-notebook"><div className="dl-section-title"><div><span>05 · {es ? 'CUADERNO CIENTÍFICO' : 'SCIENTIFIC NOTEBOOK'}</span><h2>{es ? 'Prediga, observe y explique' : 'Predict, observe and explain'}</h2></div><small>{storageError ? (es ? 'EXPORTAR PARA CONSERVAR' : 'EXPORT TO PRESERVE') : (es ? 'GUARDADO EN ESTE NAVEGADOR' : 'SAVED IN THIS BROWSER')}</small></div><div className="dl-notebook-grid">{([['hypothesis', es ? 'Mi hipótesis' : 'My hypothesis'], ['observations', es ? 'Datos y observaciones (con unidades)' : 'Data and observations (with units)'], ['conclusion', es ? 'Conclusión, incertidumbres y próximos pasos' : 'Conclusion, uncertainties and next steps']] as const).map(([key, label]) => <label key={key}>{label}<textarea aria-label={label} maxLength={20000} rows={5} value={notebook[key]} onChange={event => setNotebook(current => ({ ...current, [key]: event.target.value }))}/></label>)}</div><label className="dl-complete"><input type="checkbox" checked={notebook.complete} onChange={event => setNotebook(current => ({ ...current, complete: event.target.checked }))}/>{es ? 'Marcar esta práctica como completada' : 'Mark this practice complete'}</label><p className="dl-caption">{es ? 'El JSON exportado incluye este cuaderno, los parámetros realmente ejecutados y los datos numéricos. El guardado del navegador es local a este equipo.' : 'Exported JSON includes this notebook, actually executed parameters and numerical data. Browser saving is local to this computer.'}</p></section>

    {level >= 2 && result && <section className="dl-studies"><div className="dl-section-title"><div><span>06 · {es ? 'VARIACIÓN CONTROLADA' : 'CONTROLLED VARIATION'}</span><h2>{es ? 'Barridos y Monte Carlo' : 'Sweeps and Monte Carlo'}</h2></div><small>{es ? 'CÁLCULO LOCAL' : 'LOCAL CALCULATION'}</small></div><div className="dl-inline-fields"><label>{es ? 'Parámetro independiente' : 'Independent parameter'}<select value={studyParameter} onChange={event => setStudyParameter(event.target.value)}>{device.parameters.map(p => <option key={p.key} value={p.key}>{p.label[locale]} ({p.unit})</option>)}</select></label><label>{es ? 'Variación ± / σ (%)' : 'Variation ± / σ (%)'}<input type="number" min=".1" max="50" step=".5" value={variation} onChange={event => setVariation(Number(event.target.value))}/></label><label>{es ? 'Semilla' : 'Seed'}<input type="number" min="0" max="4294967295" step="1" value={seed} onChange={event => setSeed(Number(event.target.value))}/></label><label>{es ? 'Muestras MC' : 'MC samples'}<select value={samples} onChange={event => setSamples(Number(event.target.value))}>{[10, 20, 40].map(n => <option key={n}>{n}</option>)}</select></label></div><div className="dl-result-actions"><button disabled={dirty || !!busy || invalidFields.length > 0} onClick={() => run(result.config, { type: 'sweep', parameter: studyParameter, variation, seed, samples })}>{es ? 'Barrido de cinco valores' : 'Five-value sweep'}</button><button disabled={dirty || !!busy || invalidFields.length > 0} onClick={() => run(result.config, { type: 'montecarlo', parameter: studyParameter, variation, seed, samples })}>Monte Carlo ×{samples}</button>{study && <button onClick={() => setStudy(null)}>{es ? 'Quitar estudio' : 'Clear study'}</button>}</div><p className="dl-caption">{es ? 'Barrido: nominal ± variación. Monte Carlo: distribución normal, σ = porcentaje del valor nominal, semilla reproducible. No se recortan muestras fuera de rango: se solicita ajustar el estudio. Estas distribuciones son supuestas, no tolerancias de una fundición.' : 'Sweep: nominal ± variation. Monte Carlo: normal distribution, σ = percent of nominal, reproducible seed. Out-of-range samples are not clipped: adjust the study. These are assumed distributions, not foundry tolerances.'}</p>
      {study && stats && studyMetric && <><p>{study.runs.length} {es ? 'ejecuciones; se dibujan hasta ocho curvas en la gráfica principal. Las estadísticas y el JSON incluyen todas.' : 'runs; up to eight curves are displayed on the main plot. Statistics and JSON include all runs.'}</p><label className="dl-sampling">{es ? 'Métrica para estadística' : 'Statistical metric'}<select value={studyMetric.id} onChange={event => setStatMetric(event.target.value)}>{result.metrics.map(m => <option key={m.id} value={m.id}>{m.label[locale]} ({m.unit})</option>)}</select></label><div className="dl-metrics">{[[es ? 'Media' : 'Mean', stats.mean], ['σ', stats.standardDeviation], ['P05', stats.p05], ['P50', stats.median], ['P95', stats.p95]].map(([label, value]) => <div key={label}><span>{label}</span><b>{number(Number(value))}</b><small>{studyMetric.unit}</small></div>)}</div><Histogram values={values} unit={studyMetric.unit} locale={locale}/><p className="dl-caption">{es ? 'Los percentiles describen las muestras; no son un intervalo de confianza ni una incertidumbre de medición.' : 'Percentiles describe samples; they are not a confidence interval or measurement uncertainty.'}</p></>}
    </section>}

    {level >= 3 && result && selected && <section className="dl-measurements"><div className="dl-section-title"><div><span>07 · {es ? 'MODELO FRENTE A MEDICIÓN' : 'MODEL VERSUS MEASUREMENT'}</span><h2>{es ? 'Importe sus datos experimentales' : 'Import experimental data'}</h2></div><small>CSV · x,y[,σy]</small></div><p>{es ? `La curva seleccionada requiere x en ${selected.x_unit} e y en ${selected.y_unit}. Use dos columnas numéricas, encabezado opcional y punto decimal; tercera columna opcional para σy absoluta (1σ). Se comparan sólo puntos dentro del dominio, sin extrapolar.` : `Selected curve requires x in ${selected.x_unit} and y in ${selected.y_unit}. Use two numeric columns, optional header and decimal point; optional third column is absolute σy (1σ). Only in-domain points are compared, without extrapolation.`}</p><label className="dl-complete"><input type="checkbox" checked={unitsConfirmed} onChange={event => setUnitsConfirmed(event.target.checked)}/>{es ? `Mis columnas usan ${selected.x_unit} y ${selected.y_unit}` : `My columns use ${selected.x_unit} and ${selected.y_unit}`}</label><div className="dl-result-actions"><label className={`dl-upload ${!unitsConfirmed ? 'disabled' : ''}`}>{es ? 'Importar medición CSV' : 'Import measurement CSV'}<input type="file" disabled={!unitsConfirmed} accept=".csv,.tsv,text/csv" onChange={event => { const file = event.target.files?.[0]; if (file) void importMeasurement(file); event.currentTarget.value = '' }}/></label><button onClick={() => downloadFile('measurement-format.csv', 'x,y,sigma_y\n0.2,0.0001,0.00001\n0.3,0.0002,0.00001\n0.4,0.0003,0.00001\n', 'text/csv;charset=utf-8')}>{es ? 'Descargar formato CSV' : 'Download CSV format'}</button>{visibleMeasurement && <button onClick={() => { setMeasurement(null); setFit(null) }}>{es ? 'Quitar medición' : 'Remove measurement'}</button>}</div>{measurementError && <p className="error" role="alert">{measurementError}</p>}
      {visibleMeasurement && comparison && <><p>{visibleMeasurement.filename} · {comparison.n}/{visibleMeasurement.data.x.length} {es ? 'puntos comparados; la vista muestra hasta 500 marcas.' : 'compared points; the view displays up to 500 markers.'}</p><div className="dl-metrics"><div><span>RMSE</span><b>{number(comparison.rmse)}</b><small>{selected.y_unit}</small></div><div><span>MAE</span><b>{number(comparison.mae)}</b><small>{selected.y_unit}</small></div><div><span>R²</span><b>{number(comparison.r2)}</b><small>1</small></div></div><LabPlot locale={locale} series={{ ...selected, name: 'measurement_residuals', label: t('Residuos medición − modelo', 'Measurement − model residuals'), x: comparison.x, y: comparison.residual, y_label: 'Measurement − model', explanation: t('Residuos en las unidades originales. El modelo se interpola linealmente; compare también con una malla más densa.', 'Residuals in original units. The model is linearly interpolated; also compare a denser grid.') }}/><div className="dl-inline-fields"><label>{es ? 'x mínimo de ajuste' : 'Fit minimum x'}<input type="number" step="any" value={fitStart} onChange={event => setFitStart(Number(event.target.value))}/></label><label>{es ? 'x máximo de ajuste' : 'Fit maximum x'}<input type="number" step="any" value={fitStop} onChange={event => setFitStop(Number(event.target.value))}/></label><button onClick={() => fitMeasurement()}>{es ? 'Ajustar y = ax + b' : 'Fit y = ax + b'}</button>{selected.x_unit === 'V' && selected.y_unit === 'A' && ['pn', 'pin', 'schottky', 'zener', 'led', 'photodiode'].includes(config.device) && <button onClick={() => fitMeasurement(true)}>{es ? 'Extraer n e Is (ln I)' : 'Extract n and Is (ln I)'}</button>}</div>{fit && <div className="dl-fit-result"><p>a = {number(fit.slope)} ± {number(fit.slopeStdError)} · b = {number(fit.intercept)} ± {number(fit.interceptStdError)} · R² = {number(fit.r2)} · N = {fit.n}</p>{fit.ideality !== undefined && <p>n = {number(fit.ideality)} · Is = {number(fit.isat!)} A · T = {result.config.parameters.temperature ?? 300} K</p>}<p className="dl-caption">{es ? 'Errores estándar 1σ del ajuste. Con σy se usa regresión ponderada por 1/σy²; sin σy se estima varianza residual. En ln(I), σln I ≈ σI/I; el modelo supone I ≫ Is y una región exponencial. El ajuste no verifica por sí solo el mecanismo físico.' : 'Fit standard errors at 1σ. With σy use weights 1/σy²; without it estimate residual variance. For ln(I), σln I ≈ σI/I; the model assumes I ≫ Is and an exponential region. Fitting alone does not verify the physical mechanism.'}</p></div>}</>}
    </section>}

    <section className="dl-model"><div className="dl-section-title"><div><span>{es ? 'PROCEDENCIA Y LÍMITES' : 'PROVENANCE AND LIMITS'}</span><h2>{es ? 'La física que está usando' : 'The physics you are using'}</h2></div><small>{result?.revision ?? 'device-lab-1.0.0'}</small></div><div className="dl-model-columns"><div><h3>{es ? 'Relaciones del modelo' : 'Model relationships'}</h3>{device.equations.map(equation => <code key={equation}>{equation}</code>)}<h3>{es ? 'Supuestos y alcance' : 'Assumptions and scope'}</h3><ul>{device.assumptions.map((item, i) => <li key={i}>{item[locale]}</li>)}</ul></div><div><h3>{es ? 'Comprobaciones de consistencia' : 'Consistency checks'}</h3><ul className="dl-checks">{result?.checks.map(check => <li key={check.id} className={check.passed ? 'pass' : 'fail'}><b>{check.passed ? '✓' : '×'} {check.label[locale]}</b><span>{number(check.value)} ≤ {number(check.limit)} {check.unit}</span></li>)}</ul><p className="dl-caption">{es ? 'Estas comprobaciones verifican identidades y calidad numérica del modelo. No sustituyen mediciones, calibración, metrología ni validación de fabricación.' : 'These checks verify identities and numerical model quality. They do not replace measurements, calibration, metrology or fabrication validation.'}</p><h3>{es ? 'Fuentes y estudio adicional' : 'Sources and further study'}</h3><ul className="dl-references">{device.references.map(id => <li key={id}><a href={REFERENCES[id].url} target="_blank" rel="noreferrer">{REFERENCES[id].title} ↗</a></li>)}</ul></div></div>
      {level >= 3 && config.device === 'pn' && <><button className="dl-tcad-toggle" aria-expanded={tcadOpen} onClick={() => setTcadOpen(value => !value)}>{tcadOpen ? (es ? 'Cerrar TCAD local' : 'Close local TCAD') : (es ? 'Abrir DEVSIM local y validación de malla' : 'Open local DEVSIM and mesh validation')}</button>{tcadOpen && result && <LocalTCAD config={result.config} locale={locale}/>}</>}
      {level >= 4 && result && <details><summary>{es ? 'Configuración exacta de la última ejecución' : 'Exact last-run configuration'}</summary><pre className="dl-json">{JSON.stringify(result.config, null, 2)}</pre></details>}
    </section>

    <FabricationFlow locale={locale} onDevice={id => { chooseDevice(id); scrollToBench() }}/>
    <section className="dl-guide-library"><div className="dl-section-title"><div><span>{es ? 'RUTAS DE APRENDIZAJE' : 'LEARNING PATHS'}</span><h2>{es ? 'El siguiente experimento' : 'The next experiment'}</h2></div><input type="search" aria-label={es ? 'Buscar experimento' : 'Search experiments'} value={guideSearch} onChange={event => setGuideSearch(event.target.value)} placeholder={es ? 'Hipótesis, proceso o dispositivo…' : 'Hypothesis, process or device…'}/></div><p className="dl-caption">{es ? `${guides.length} guías para el nivel actual. Avanzado e Investigación añaden extracción de parámetros, comparación de mediciones y controles numéricos. Cada práctica conserva un cuaderno propio.` : `${guides.length} guides for the current level. Advanced and Research add parameter extraction, measurement comparison and numerical controls. Each practice keeps its own notebook.`}</p><div className="dl-guides">{guides.map(g => <button key={g.id} aria-pressed={g.id === guideId} onClick={() => { chooseGuide(g); scrollToBench() }}><span>{getDevice(g.device).symbol} · {(es ? ['Explorar', 'Aprender', 'Diseñar', 'Avanzado', 'Investigación'] : MODES)[g.level]}</span><b>{g.title[locale]}</b><small>{g.question[locale]}</small></button>)}</div></section>
    <section className="dl-glossary"><h2>{es ? 'Las palabras, en contexto' : 'Words in context'}</h2><dl>{[
      [t('Electrón y hueco', 'Electron and hole'), t('El electrón tiene carga negativa. Un hueco representa la ausencia de un electrón y se comporta como portador positivo.', 'An electron is negatively charged. A hole represents a missing electron and behaves as a positive carrier.')],
      [t('Dopaje', 'Doping'), t('Átomos añadidos cambian cuántos portadores están disponibles. Donantes favorecen electrones y aceptores huecos.', 'Added atoms change carrier availability. Donors favor electrons and acceptors favor holes.')],
      [t('Agotamiento', 'Depletion'), t('Región con pocos portadores móviles; conserva los iones fijos que crean el campo eléctrico.', 'Region with few mobile carriers; fixed ions remain and create the electric field.')],
      [t('Corriente convencional', 'Conventional current'), t('Se define en la dirección de movimiento de carga positiva. Es opuesta al movimiento de electrones.', 'Defined in the direction of positive-charge motion. It is opposite to electron motion.')],
      [t('Modelo y medición', 'Model and measurement'), t('El modelo predice bajo ciertos supuestos. La medición observa un sistema real con incertidumbre; compararlos exige unidades y condiciones equivalentes.', 'A model predicts under assumptions. A measurement observes a real system with uncertainty; comparison requires equivalent units and conditions.')],
      [t('Malla y muestreo', 'Mesh and sampling'), t('La malla de TCAD discretiza ecuaciones espaciales. El muestreo de una curva analítica decide dónde dibujarla; aumentar puntos no agrega física.', 'A TCAD mesh discretizes spatial equations. Analytic-curve sampling determines drawing points; more points do not add physics.')],
    ].map(([term, definition]) => <div key={term.en}><dt>{term[locale]}</dt><dd>{definition[locale]}</dd></div>)}</dl></section>
  </main>
}
