import { readFile } from 'node:fs/promises'
import { expect, test, type Page } from '@playwright/test'
import { DEVICES, GUIDES } from '../../src/deviceLab/catalogue'

async function ready(page: Page) { await expect(page.getByTestId('lab-status')).toHaveText('CALCULADO') }
async function jsonExport(page: Page) {
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar experimento JSON', exact: true }).click()
  return JSON.parse(await readFile((await (await download).path())!, 'utf8'))
}
test.beforeEach(async ({ page }) => {
  // Offline Design Studio uses its shipped templates. Device models must not
  // depend on a live API or any SMTP/production service.
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { detail: 'offline fixture' } }))
  await page.route('https://fonts.googleapis.com/**', route => route.abort())
  await page.goto('/tests/browser/device-lab.html')
  await page.getByRole('button', { name: 'Laboratorio de dispositivos', exact: true }).click()
  await ready(page)
})

test('all 33 modules execute in client workers and the main navigation remains usable', async ({ page }) => {
  test.setTimeout(60000)
  const errors: string[] = [], simulationRequests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (/simulate|experiment|127\.0\.0\.1:8787/.test(request.url())) simulationRequests.push(request.url()) })
  await expect(page.locator('.dl-device-grid>button')).toHaveCount(33)
  await expect(page.locator('.dl-hero-facts')).toContainText(String(GUIDES.length))
  for (const device of DEVICES) {
    await page.locator(`[data-device="${device.id}"]`).click()
    await ready(page)
    await expect(page.locator('.dl-controls h2')).toHaveText(device.name.es)
    await expect(page.locator('.dl-results .plot svg')).toBeVisible()
    await expect(page.locator('.dl-checks .fail')).toHaveCount(0)
    const geometry = await page.locator('.dl-results .plot svg').innerHTML()
    expect(geometry, device.id).not.toMatch(/NaN|Infinity/)
    await expect(page.locator('.dl-controls [role=alert]')).toHaveCount(0)
  }
  expect(errors).toEqual([])
  expect(simulationRequests).toEqual([])
  await expect(page.getByRole('button', { name: 'Equipo', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Estudio de diseño', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Mis proyectos', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Laboratorio de dispositivos', exact: true }).click()
  await ready(page)
  await page.getByRole('button', { name: 'Equipo', exact: true }).click()
  await expect(page).toHaveURL(/#\/equipo$/)
})

test('input validation, saved references and signed CSV/SVG exports preserve executed parameters', async ({ page }) => {
  await page.getByRole('button', { name: 'Investigación', exact: true }).click()
  await page.getByRole('button', { name: 'Guardar referencia', exact: true }).click()
  const doping = page.getByLabel('Aceptores NA (lado P)', { exact: true })
  await doping.fill('invalid')
  await expect(page.getByRole('button', { name: /Ejecutar experimento/ })).toBeDisabled()
  await expect(doping).toHaveAttribute('aria-invalid', 'true')
  await page.getByRole('button', { name: 'Restaurar parámetros iniciales', exact: true }).click()
  await ready(page)
  await expect(doping).toHaveAttribute('aria-invalid', 'false')
  await expect(doping).toHaveValue('1e+16')
  await doping.fill('1e17'); await doping.press('Tab')
  await expect(page.locator('.dl-controls [role=status]')).toContainText('Parámetros modificados')
  const before = await jsonExport(page)
  expect(before.result.config.parameters.na).toBe(1e16)
  await page.getByRole('button', { name: /Ejecutar experimento/ }).click()
  await ready(page)
  const after = await jsonExport(page)
  expect(after.result.config.parameters.na).toBe(1e17)
  expect(after.input_sha256).not.toBe(before.input_sha256)
  await expect(page.locator('.dl-results .plot-legend')).toContainText('Referencia guardada')
  await page.locator('.dl-plot-tabs').getByRole('button', { name: 'Curva I–V', exact: true }).click()
  await page.locator('.dl-results').getByLabel('Log eje Y', { exact: true }).check()
  await expect(page.locator('.dl-results .dl-plot')).toContainText('se omiten')
  const svgDownload = page.waitForEvent('download')
  await page.locator('.dl-results').getByRole('button', { name: 'Exportar SVG', exact: true }).click()
  const svg = await readFile((await (await svgDownload).path())!, 'utf8')
  expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"')
  expect(svg).toContain('primary_data_class')
  expect(svg).toContain('log10 positive')
  expect(svg).toContain('stroke-width:')
  expect(svg).not.toMatch(/NaN|Infinity/)
  const csvDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar CSV de curva', exact: true }).click()
  const csv = await readFile((await (await csvDownload).path())!, 'utf8')
  expect(csv.split('\n')).toHaveLength(202)
  expect(csv).toContain('(V)')
  expect(csv).toContain('(A)')
  expect(Number(csv.split('\n')[1].split(',')[1].replaceAll('"', ''))).toBeLessThan(0)
})

test('seeded Monte Carlo exports every sample and notebooks survive reload', async ({ page }) => {
  await page.getByRole('button', { name: 'Investigación', exact: true }).click()
  await page.getByLabel('Mi hipótesis', { exact: true }).fill('La región menos dopada se agota más.')
  await page.getByRole('combobox', { name: 'Muestras MC', exact: true }).selectOption('10')
  await page.getByRole('button', { name: 'Monte Carlo ×10', exact: true }).click()
  await ready(page)
  await expect(page.locator('.dl-histogram')).toBeVisible()
  const first = await jsonExport(page)
  expect(first.execution.host).toBe('client-browser')
  expect(first.execution.authoritative).toBe(false)
  expect(first.study.runs).toHaveLength(10)
  expect(first.notebook.hypothesis).toBe('La región menos dopada se agota más.')
  expect(first.result.config.parameters.na).toBe(1e16)
  await page.getByRole('button', { name: 'Monte Carlo ×10', exact: true }).click()
  await ready(page)
  const second = await jsonExport(page)
  expect(second.study).toEqual(first.study)
  await page.reload()
  await page.getByRole('button', { name: 'Laboratorio de dispositivos', exact: true }).click()
  await ready(page)
  await expect(page.getByLabel('Mi hipótesis', { exact: true })).toHaveValue(first.notebook.hypothesis)
})

test('imported measurements require units and weighted diode fitting distinguishes them from model data', async ({ page }) => {
  await page.getByRole('button', { name: 'Investigación', exact: true }).click()
  await page.locator('.dl-plot-tabs').getByRole('button', { name: 'Curva I–V', exact: true }).click()
  const upload = page.locator('.dl-measurements input[type=file]')
  await expect(upload).toBeDisabled()
  await page.locator('.dl-measurements .dl-complete input').check()
  const vt = 1.380649e-23 * 300 / 1.602176634e-19
  const csv = 'Voltage,Current,Sigma\n' + [.2, .25, .3, .35, .4, .45, .5].map(v => { const i = 2e-12 * Math.exp(v / (1.4 * vt)); return `${v},${i},${i * .01}` }).join('\n')
  await upload.setInputFiles({ name: 'diode-measured.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await expect(page.locator('.dl-measurements')).toContainText('7/7 puntos comparados')
  await expect(page.locator('.dl-results .plot-legend')).toContainText('Medición importada')
  await page.getByRole('button', { name: 'Extraer n e Is (ln I)', exact: true }).click()
  await expect(page.locator('.dl-fit-result')).toContainText('n = 1.4')
  const bundle = await jsonExport(page)
  expect(bundle.notebook.fit.ideality).toBeCloseTo(1.4, 7)
  expect(bundle.notebook.fit.isat).toBeCloseTo(2e-12, 14)
  expect(bundle.notebook.measurement.filename).toBe('diode-measured.csv')
  expect(bundle.notebook.measurement.data.sigma).toHaveLength(7)
  const svgDownload = page.waitForEvent('download')
  await page.locator('.dl-results').getByRole('button', { name: 'Exportar SVG', exact: true }).click()
  const svg = await readFile((await (await svgDownload).path())!, 'utf8')
  expect(svg).toContain('user-supplied measurement')
  expect(svg).toContain('<circle')
})

test('carrier animation starts paused, stops offscreen and runs without simulation requests', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const carrier = page.locator('.carrier-view'), canvas = carrier.locator('canvas')
  await canvas.scrollIntoViewIfNeeded()
  await expect(carrier.getByRole('button', { name: 'Animar portadores', exact: true })).toHaveAttribute('aria-pressed', 'false')
  const signature = () => canvas.evaluate((element: HTMLCanvasElement) => element.toDataURL())
  const original = await signature()
  await page.waitForTimeout(150)
  expect(await signature()).toBe(original)
  const requests: string[] = []
  page.on('request', request => { if (/api|8787/.test(request.url())) requests.push(request.url()) })
  await carrier.getByRole('button', { name: 'Animar portadores', exact: true }).click()
  await expect.poll(signature).not.toBe(original)
  await page.locator('.dl-glossary').scrollIntoViewIfNeeded()
  // Let the observer deliver its final visible frame, then assert a stable canvas.
  await page.waitForTimeout(150)
  const hidden = await signature()
  await page.waitForTimeout(180)
  expect(await signature()).toBe(hidden)
  await canvas.scrollIntoViewIfNeeded()
  await expect.poll(signature).not.toBe(hidden)
  await carrier.getByRole('button', { name: 'Pausar portadores', exact: true }).click()
  const paused = await signature()
  await page.waitForTimeout(150)
  expect(await signature()).toBe(paused)
  expect(requests).toEqual([])
})

test('fabrication steps open related experiments and the responsive catalogue works in both languages', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const fabrication = page.getByRole('region', { name: 'Recorrido de fabricación', exact: true })
  await fabrication.getByRole('button', { name: /Resist y exposición/ }).click()
  await expect(fabrication.locator('h4')).toHaveText('Resist y exposición')
  await fabrication.getByRole('button', { name: /Abrir experimento relacionado/ }).click()
  await ready(page)
  await expect(page.locator('.dl-controls h2')).toHaveText('Fotolitografía óptica')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(391)
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(page.locator('.dl-controls h2')).toHaveText('Optical photolithography')
  await page.getByLabel('Search devices', { exact: true }).fill('mosfet')
  await expect(page.locator('.dl-device-grid>button')).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Team', exact: true })).toBeVisible()
})

test('PN TCAD and mesh validation send their jobs directly to the client companion', async ({ page }) => {
  const jobs: { url: string; body: any }[] = [], serverSimulations: string[] = []
  page.on('request', request => {
    if (request.method() === 'POST' && /simulations|validation/.test(request.url()) && !request.url().startsWith('http://127.0.0.1:8787/')) serverSimulations.push(request.url())
  })
  // This fixture verifies routing/contracts, not the physics of the native
  // solver; the companion's integration suite runs real DEVSIM separately.
  const result = { experiment_name: 'local routing fixture', metrics: [{ label: 'Fixture voltage', value: .714, unit: 'V' }], series: [{ name: 'potential', x_label: 'Position', x_unit: 'µm', y_label: 'Potential', y_unit: 'V', x: [-1, 0, 1], y: [0, .357, .714] }], explanations: [], warnings: [], converged: true, provenance: { engine: 'devsim', engine_version: 'routing-fixture', model: 'fixture-only', input_sha256: 'abc123', authoritative: false, execution_host: 'local-companion' } }
  await page.route('http://127.0.0.1:8787/**', async route => {
    const request = route.request(), headers = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS', 'Access-Control-Allow-Headers': 'content-type' }
    if (request.method() === 'OPTIONS') { await route.fulfill({ status: 204, headers }); return }
    if (request.url().endsWith('/health')) { await route.fulfill({ headers, json: { ok: true } }); return }
    jobs.push({ url: request.url(), body: request.postDataJSON() })
    await route.fulfill({ headers, json: request.url().includes('/validation/') ? { passed: true, checks: [{ id: 'fixture', label: 'Routing fixture', value: 0, limit: 1, passed: true }], result, bundle: { bundle_sha256: 'fixture', result } } : result })
  })
  await page.getByRole('button', { name: 'Avanzado', exact: true }).click()
  expect(jobs).toEqual([])
  await page.getByRole('button', { name: 'Abrir DEVSIM local y validación de malla', exact: true }).click()
  const tcad = page.locator('.dl-tcad')
  await expect(tcad).toContainText('LOCAL CONECTADO')
  await tcad.getByRole('button', { name: 'Ejecutar TCAD local', exact: true }).click()
  await expect(tcad).toContainText('Fixture voltage')
  expect(jobs[0].url).toBe('http://127.0.0.1:8787/api/v1/simulations/pn-junction')
  expect(jobs[0].body.engine).toBe('devsim')
  expect(jobs[0].body.device.acceptor_cm3).toBe(1e16)
  await tcad.getByRole('button', { name: 'Validar 51 / 101 / 201', exact: true }).click()
  await expect(tcad).toContainText('Routing fixture')
  expect(jobs[1].url).toBe('http://127.0.0.1:8787/api/v1/validation/pn-junction')
  expect(jobs[1].body.mesh_points).toEqual([51, 101, 201])
  expect(serverSimulations).toEqual([])
  const svgDownload = page.waitForEvent('download')
  await tcad.getByRole('button', { name: 'Exportar SVG', exact: true }).click()
  const svg = await readFile((await (await svgDownload).path())!, 'utf8')
  expect(svg).toContain('local-companion')
  expect(svg).toContain('fixture-only')
  expect(svg).toContain('acceptor_cm3')
})
