import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.goto('/tests/browser/editor.html') })

test('colored editing keeps autosave, cursor, undo, indentation and file switching', async ({ page }) => {
  const editor = page.locator('.code-editor .cm-content')
  await expect(editor.locator('.syntax-comment')).toContainText('reset signal')
  await expect(editor.locator('.syntax-keyword').first()).toContainText('module')
  await expect(page.locator('.cm-lineNumbers')).toBeVisible()
  const original = await page.getByTestId('source').textContent()
  await editor.click(); await page.keyboard.press('Control+End'); await page.keyboard.insertText('// añadido\n')
  await expect(page.getByTestId('source')).toHaveText(original + '// añadido\n')
  await expect(page.locator('.code-editor-status')).toContainText('Ln 6, Col 1')
  await page.keyboard.press('Control+z')
  await expect(page.getByTestId('source')).toHaveText(original!)
  await page.keyboard.press('Tab'); await page.keyboard.insertText('// indentado')
  await expect(page.getByTestId('source')).toHaveText(original + '  // indentado')
  await page.getByLabel('Archivo').selectOption('README.md')
  await expect(editor.locator('.syntax-heading').last()).toContainText('Primeros pasos')
  await page.getByLabel('Archivo').selectOption('script.py')
  await expect(editor.locator('.syntax-comment')).toContainText('calibración')
  await page.getByLabel('Archivo').selectOption('top.sv')
  await expect(page.getByTestId('source')).toHaveText(original + '  // indentado')
})

test('find, wrapping and external changes remain usable', async ({ page }) => {
  await page.getByRole('button', { name: /Buscar/ }).click()
  await expect(page.locator('.cm-search')).toBeVisible()
  await page.locator('.cm-search input[name=search]').fill('ready')
  await expect(page.locator('.cm-searchMatch').first()).toBeVisible()
  await page.getByRole('button', { name: 'Ajustar líneas' }).click()
  await expect(page.locator('.code-editor .cm-content')).toHaveClass(/cm-lineWrapping/)
  await page.getByRole('button', { name: 'Actualizar contenido externo' }).click()
  await expect(page.getByTestId('source')).toContainText('// external update')
  await expect(page.locator('.code-editor .cm-content')).toContainText('// external update')
})

test('console colors tags and timestamps while keeping the content read-only and safe', async ({ page }) => {
  const log = page.locator('.log-output')
  await expect(log.locator('.log-time').first()).toContainText('2026-10-09')
  await expect(log.locator('.log-tag')).toContainText('YOSYS')
  await expect(log.locator('.log-warning').first()).toContainText('WARNING')
  await expect(log.locator('.log-error').first()).toContainText('ERROR')
  await expect(log.locator('.log-success').first()).toContainText('PASS')
  const colors = await Promise.all(['.log-time', '.log-tag', '.log-error', '.log-success'].map(selector => log.locator(selector).first().evaluate(element => getComputedStyle(element).color)))
  expect(new Set(colors).size).toBe(4)
  expect(await page.evaluate(() => (window as any).injected)).toBeUndefined()
  await log.locator('.cm-content').click(); await page.keyboard.type('attempted edit')
  await expect(log).not.toContainText('attempted edit')
})

test('large logs use a viewport and still copy the entire output', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: 'Log largo' }).click()
  const log = page.locator('.log-output')
  await expect.poll(() => log.locator('.cm-line').count()).toBeLessThan(500)
  await page.getByRole('button', { name: 'Seleccionar todo', exact: true }).click()
  await page.keyboard.press('Control+c')
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain('PASS FINAL MARKER')
  await page.getByRole('button', { name: 'Copiar consola' }).click()
  const expected = await page.getByTestId('log').textContent()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(expected)
  await page.getByRole('button', { name: 'Agregar log' }).click()
  await page.getByRole('button', { name: 'Copiar consola' }).click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain('APPENDED MARKER')
})
