type Text = { es: string; en: string }
const t = (es: string, en: string): Text => ({ es, en })
export interface GuideChapter {
  id: string; title: Text; summary: Text; image?: string; callouts?: Text[]
  steps: { title: Text; body: Text }[]; checkpoint: Text; tip: Text
}

export const GUIDE: GuideChapter[] = [
  {
    id: 'access', title: t('Entrar y orientarse', 'Sign in and find your way'),
    summary: t('Una cuenta personal conecta sus proyectos con el portal. La navegación conserva el acceso al estudio, al laboratorio, al equipo y a esta guía.', 'A personal account connects your projects to the portal. Navigation keeps the studio, device lab, team and this guide accessible.'),
    image: 'access.jpg', callouts: [t('Registro y acceso a la cuenta.', 'Registration and account access.'), t('Correo y contraseña de su cuenta.', 'Your account email and password.'), t('Recuperación de acceso.', 'Account recovery.')],
    steps: [
      { title: t('Cree su cuenta', 'Create your account'), body: t('Abra Registro, escriba su nombre, un correo institucional admitido y una contraseña propia. Si su dominio no está permitido, use la solicitud de acceso disponible en el registro.', 'Open Register and enter your name, an accepted institutional email and your own password. If your domain is not allowed, use the access request provided on the registration page.') },
      { title: t('Verifique el correo', 'Verify your email'), body: t('Abra el enlace que recibe en su bandeja y después inicie sesión. Revise también spam. La verificación confirma que controla ese correo; crear una cuenta no concede permisos de administrador.', 'Open the link in your inbox, then sign in. Check spam as well. Verification confirms control of the email address; registration does not grant administrator privileges.') },
      { title: t('Entre al Lab', 'Enter the Lab'), body: t('El estudio de diseño organiza proyectos y herramientas EDA. El laboratorio de dispositivos permite explorar física y experimentos. ES/EN cambia el idioma; Equipo conserva la información del proyecto.', 'The design studio organizes projects and EDA tools. The device lab explores physics and experiments. ES/EN changes the language; Team preserves project information.') },
      { title: t('Recupere su sesión', 'Recover your session'), body: t('Use la recuperación de contraseña si perdió acceso. Cada cuenta ve sus propios trabajos físicos: conocer el identificador de otro usuario no permite abrirlo ni cancelarlo.', 'Use password recovery if you lose access. Each account sees its own physical jobs: knowing another user’s identifier does not let you open or cancel it.') },
    ], checkpoint: t('Puede iniciar sesión con su cuenta verificada y abrir el laboratorio.', 'You can sign in with your verified account and open the lab.'),
    tip: t('Si no llega la verificación, el administrador debe revisar el servicio SMTP. No comparta contraseñas en proyectos ni en capturas.', 'If verification does not arrive, the administrator needs to check SMTP. Keep passwords out of projects and screenshots.'),
  },
  {
    id: 'studio', title: t('Crear, importar y guardar proyectos', 'Create, import and save projects'),
    summary: t('Empiece con una plantilla funcional y comentada. Mantenga fuentes, pruebas, restricciones y documentación juntas para que cada resultado tenga un contexto reproducible.', 'Start with a functional, commented template. Keep sources, tests, constraints and documentation together so each result has reproducible context.'),
    image: 'studio.jpg', callouts: [t('Biblioteca de plantillas y objetivo del diseño.', 'Template library and design objective.'), t('Configuración del proyecto y PDK.', 'Project settings and PDK.'), t('Crear el flujo de diseño.', 'Create the design flow.')],
    steps: [
      { title: t('Elija un punto de partida', 'Choose a starting point'), body: t('Seleccione microcontrolador, FPGA, bloque analógico, interfaz de sensor, RF, celda estándar o proyecto en blanco según su objetivo. Lea el README de la plantilla: describe archivos, pruebas, criterios de aceptación y cómo modificarla.', 'Choose a microcontroller, FPGA, analog block, sensor interface, RF, standard cell or blank project for your objective. Read its README for files, tests, acceptance criteria and customization instructions.') },
      { title: t('Defina el alcance', 'Set the scope'), body: t('Asigne un nombre, nivel, lenguaje disponible y PDK. El PDK establece bibliotecas y reglas del proceso. Una opción visible en el catálogo puede tener solo documentación o un adaptador pendiente; revise su estado antes de planear RTL→GDSII.', 'Set a name, level, supported language and PDK. The PDK supplies process libraries and rules. A listed option may offer documentation only or have a pending adapter; check readiness before planning RTL→GDSII.') },
      { title: t('Genere el proyecto', 'Generate the project'), body: t('Pulse Crear flujo de diseño para abrir el espacio de trabajo. Para empezar, use una plantilla digital pequeña y un PDK físico disponible; aprenda primero con las pruebas que ya incluye.', 'Click Create design flow to open the workspace. Start with a small digital template and an available physical PDK, learning first from its included tests.') },
      { title: t('Importe y conserve una copia', 'Import and keep a copy'), body: t('La biblioteca permite importar un proyecto JSON o un repositorio público de GitHub. Dentro del proyecto, Fuentes .zip guarda sus archivos y Exportar JSON conserva la estructura del proyecto. Los cambios se guardan en el navegador y se sincronizan con su cuenta cuando hay conexión.', 'The library imports a project JSON or a public GitHub repository. Inside a project, Sources .zip saves files and Export JSON preserves the project structure. Changes are saved in the browser and synced to your account when connected.') },
    ], checkpoint: t('Tiene un proyecto con documentación, fuentes y al menos una prueba identificada.', 'You have a project with documentation, sources and at least one identified test.'),
    tip: t('Descargue una copia antes de cambios importantes. La copia de fuentes y los artefactos de ejecución son descargas diferentes.', 'Download a copy before major edits. Sources and execution artifacts are separate downloads.'),
  },
  {
    id: 'flow', title: t('Por qué trabajar en un flujo continuo', 'Why work in a continuous flow'),
    summary: t('Cada etapa responde una pregunta distinta: qué construí, si la lógica es coherente, si funciona en el tiempo, si puede implementarse y qué evidencia obtuve. Avanzar con esas respuestas reduce errores costosos y hace que una mejora sea medible.', 'Each stage answers a different question: what was built, whether the logic is coherent, whether it behaves over time, whether it can be implemented and what evidence was obtained. Answering them in order reduces costly mistakes and makes improvements measurable.'),
    steps: [
      { title: t('01 · Diseño: exprese la intención', '01 · Design: express intent'), body: t('Escriba interfaces, RTL o circuito, pruebas y restricciones. Defina qué comportamiento espera y cómo reconocerá un fallo. Un testbench forma parte del experimento, no es un archivo accesorio.', 'Write interfaces, RTL or circuit, tests and constraints. Define expected behavior and how to recognize failure. A testbench is part of the experiment, not an incidental file.') },
      { title: t('02 · Verificación: descarte errores baratos', '02 · Verification: remove inexpensive errors'), body: t('Lint revisa construcciones problemáticas; síntesis verifica que la lógica puede convertirse en una netlist; formal estudia propiedades bajo sus supuestos. Corregir aquí evita ocupar un turno físico para descubrir un módulo inexistente o una señal mal conectada.', 'Lint checks problematic constructs; synthesis checks that logic can become a netlist; formal examines properties under stated assumptions. Fixing issues here avoids reserving a physical slot to discover a missing module or a miswired signal.') },
      { title: t('03 · Simulación: observe el comportamiento', '03 · Simulation: observe behavior'), body: t('Compruebe reset, reloj, entradas, esquinas y criterios de aceptación. En HDL observe ondas y assertions; en circuitos analógicos revise barridos, transitorios y medidas. Una gráfica debe responder a una hipótesis concreta.', 'Check reset, clock, inputs, corners and acceptance criteria. In HDL inspect waveforms and assertions; in analog circuits examine sweeps, transients and measurements. A plot should answer a specific hypothesis.') },
      { title: t('04 · Implementación: añada realidad física', '04 · Implementation: add physical constraints'), body: t('Para RTL digital compatible, LibreLane conecta síntesis, floorplan, placement, árbol de reloj, routing y sign-off usando el PDK y el SDC. Área, cableado y parasíticos pueden revelar problemas que una simulación lógica ideal no mostraba.', 'For supported digital RTL, LibreLane connects synthesis, floorplan, placement, clock tree, routing and sign-off using the PDK and SDC. Area, wiring and parasitics can expose problems absent from ideal logic simulation.') },
      { title: t('05 · Resultados: cierre el ciclo', '05 · Results: close the loop'), body: t('Compare evidencia con su objetivo. Si falla temporización, revise arquitectura o restricciones; si hay congestión, revise utilización y floorplan. Cambie una variable por vez, vuelva a verificar y compare ejecuciones. Conservar configuración y reportes permite explicar por qué mejoró o empeoró.', 'Compare evidence with your objective. For timing failures review architecture or constraints; for congestion review utilization and floorplan. Change one variable at a time, verify again and compare runs. Keeping configuration and reports explains why a change helped or hurt.') },
    ], checkpoint: t('Puede relacionar una fuente, una prueba y una restricción con el resultado que está evaluando.', 'You can connect a source, a test and a constraint to the result being evaluated.'),
    tip: t('No todos los proyectos recorren la misma ruta: SPICE estudia circuitos; nextpnr implementa FPGA; TCAD estudia dispositivos. RTL→GDSII necesita RTL digital y un adaptador físico preparado, y no convierte automáticamente un circuito analógico en un chip fabricable.', 'Projects follow different paths: SPICE studies circuits, nextpnr implements FPGA and TCAD studies devices. RTL→GDSII requires digital RTL and a ready physical adapter; it does not automatically convert an analog circuit into a manufacturable chip.'),
  },
  {
    id: 'design', title: t('Editar fuentes y documentación', 'Edit sources and documentation'),
    summary: t('El espacio de trabajo mantiene el árbol de archivos, el editor, las cinco etapas y la consola cerca. Abra la etapa que necesita y vuelva a las fuentes cuando una prueba señale un problema.', 'The workspace keeps the file tree, editor, five stages and console together. Open the stage you need and return to sources when a test identifies an issue.'),
    image: 'design.jpg', callouts: [t('Navegación por las cinco etapas.', 'Navigation through the five stages.'), t('Árbol de archivos y archivo seleccionado.', 'File tree and selected file.'), t('Editor con sintaxis, comentarios y números de línea.', 'Editor with syntax, comments and line numbers.'), t('Consola de la etapa activa.', 'Console for the active stage.')],
    steps: [
      { title: t('Lea antes de modificar', 'Read before editing'), body: t('Abra README.md, docs/QUICKSTART.md y los documentos de personalización y aceptación de la plantilla. Después ubique fuentes, testbenches, restricciones y modelos. project.json especifica módulos de ejecución y opciones del proyecto.', 'Open README.md, docs/QUICKSTART.md and the template’s customization and acceptance documents. Then locate sources, testbenches, constraints and models. project.json specifies execution modules and project options.') },
      { title: t('Edite con contexto', 'Edit with context'), body: t('Seleccione un archivo en el árbol. Los colores distinguen palabras clave, comentarios, números y cadenas; las líneas y la indentación ayudan a localizar errores. Use Ctrl/Cmd+F para buscar y Ctrl/Cmd+Z para deshacer.', 'Select a file in the tree. Colors distinguish keywords, comments, numbers and strings; line numbers and indentation help locate errors. Use Ctrl/Cmd+F to search and Ctrl/Cmd+Z to undo.') },
      { title: t('Organice entradas ejecutables', 'Organize executable inputs'), body: t('Use rutas claras como rtl/uart.sv y tb/tb_uart.sv. Revise el rol del archivo y el módulo top: una fuente del circuito y un banco de pruebas tienen funciones diferentes. La implementación física usa fuentes RTL, mientras la simulación necesita además estímulos y un testbench compatible.', 'Use clear paths such as rtl/uart.sv and tb/tb_uart.sv. Check the file role and top module: circuit sources and testbenches serve different purposes. Physical implementation uses RTL sources; simulation also needs stimuli and a compatible testbench.') },
      { title: t('Interprete la consola', 'Read the console'), body: t('Seleccione una etapa para ver su registro. Los colores separan timestamps, etiquetas, avisos y errores. Seleccionar todo y Copiar todo facilitan revisar un fallo; minimice la consola para ampliar el espacio del editor.', 'Select a stage to see its log. Colors separate timestamps, tags, warnings and errors. Select all and Copy all help inspect failures; minimize the console to increase editor space.') },
    ], checkpoint: t('Identifica el top del diseño, el top de la prueba y el archivo de restricciones sin confundirlos.', 'You can identify the design top, testbench top and constraint file.'),
    tip: t('El envío físico toma una copia de las fuentes y restricciones en ese momento. Editar después no modifica el trabajo que ya está en cola o ejecutándose.', 'Physical submission takes a snapshot of sources and constraints at that moment. Later edits do not change the queued or running job.'),
  },
  {
    id: 'verification', title: t('Verificar antes de gastar un turno', 'Verify before reserving a slot'),
    summary: t('Combine varias comprobaciones. Cada herramienta cubre una clase de errores y ninguna sustituye por sí sola al resto.', 'Combine checks. Each tool covers a different class of errors, and no single tool replaces the others.'),
    image: 'verification.jpg', callouts: [t('Analizar RTL y sintetizar.', 'Lint RTL and synthesize.'), t('Herramientas especializadas y requisitos de entrada.', 'Specialized tools and input requirements.'), t('Registro y estado de la comprobación.', 'Check log and status.')],
    steps: [
      { title: t('Analice el RTL', 'Lint the RTL'), body: t('Abra Verificación y pulse Analizar RTL. Revise el primer error y su archivo/línea. Corrija referencias, anchuras, construcciones no admitidas y conexiones antes de avanzar. Evalúe también los avisos según su efecto en el diseño.', 'Open Verification and click Lint RTL. Inspect the first error and its file/line. Fix references, widths, unsupported constructs and connections before proceeding. Assess warnings by their effect on the design too.') },
      { title: t('Sintetice la lógica', 'Synthesize the logic'), body: t('Pulse Sintetizar y revise jerarquía, celdas y netlist generada. Use el módulo RTL real como top. El éxito de síntesis demuestra que esa configuración pudo procesarse; todavía no demuestra cierre de temporización ni ausencia de errores funcionales.', 'Click Synthesize and inspect hierarchy, cells and the generated netlist. Use the actual RTL module as top. Synthesis success shows that the configuration was processed; it does not yet establish timing closure or functional correctness.') },
      { title: t('Use formal con supuestos explícitos', 'Use formal with explicit assumptions'), body: t('Cuando haya archivos compatibles, configure profundidad y modo de SymbiYosys. BMC explora un número limitado de pasos; un resultado inconcluso necesita investigación. Preserve assertions, assumptions y la configuración utilizada para interpretar un PASS.', 'With compatible files, configure SymbiYosys depth and mode. BMC explores a bounded number of steps; an inconclusive result needs investigation. Keep assertions, assumptions and the configuration to interpret a PASS.') },
      { title: t('Elija FPGA cuando corresponda', 'Choose FPGA when appropriate'), body: t('Implementar FPGA usa su top, dispositivo, encapsulado, frecuencia y restricciones de pines. nextpnr no sigue el mismo proceso que un ASIC: revise recursos e I/O de la placa antes de cambiar parámetros.', 'Implement FPGA uses its top, device, package, frequency and pin constraints. nextpnr follows a different process from an ASIC: review board resources and I/O before changing parameters.') },
    ], checkpoint: t('Los errores de estructura están resueltos y entiende el alcance de cada PASS o resultado inconcluso.', 'Structural errors are resolved, and you understand the scope of every PASS or inconclusive result.'),
    tip: t('Un botón deshabilitado indica una herramienta no disponible o entradas incompatibles. Consulte la cobertura de herramientas y el aviso del botón.', 'A disabled button means a tool is unavailable or its inputs are incompatible. Check tool coverage and the button’s explanation.'),
  },
  {
    id: 'simulation', title: t('Simular y leer ondas o curvas', 'Simulate and read waveforms or curves'),
    summary: t('Observe cómo responde el diseño a entradas concretas. Defina primero qué medirá, en qué rango y qué comportamiento aceptará.', 'Observe how the design responds to specific inputs. First define what to measure, over which range and what behavior is acceptable.'),
    image: 'simulation.jpg', callouts: [t('Ejecutar el banco de pruebas compatible.', 'Run the compatible testbench.'), t('Resultado y registro de la simulación.', 'Simulation result and log.'), t('Ondas y señales para inspeccionar.', 'Waveforms and signals to inspect.')],
    steps: [
      { title: t('Prepare estímulos y comprobaciones', 'Prepare stimuli and checks'), body: t('En HDL asegure un reloj, un reset, entradas y assertions o comparaciones de salida. Verilog/SystemVerilog usa Icarus y VHDL usa GHDL según las entradas disponibles. Verifique el top del testbench en project.json.', 'For HDL provide a clock, reset, inputs and assertions or output comparisons. Verilog/SystemVerilog uses Icarus and VHDL uses GHDL when corresponding inputs are available. Check the testbench top in project.json.') },
      { title: t('Siga los eventos', 'Follow events'), body: t('Ejecute la simulación, confirme el código de salida y examine el VCD en el visor de ondas. Busque transiciones alrededor de reset y flancos de reloj; seleccione señales y use los controles de zoom o reproducción para seguir la secuencia.', 'Run the simulation, check its exit code and inspect the VCD in the waveform viewer. Look at transitions around reset and clock edges; select signals and use zoom or playback controls to follow the sequence.') },
      { title: t('Mida circuitos analógicos', 'Measure analog circuits'), body: t('Para SPICE seleccione el testbench o netlist correcto y ejecute ngspice o Xyce cuando esté disponible. Compare DC, AC o transitorio con sus criterios de aceptación. Los modelos genéricos de una plantilla sirven como punto de partida; para un proceso concreto sustituya los modelos y revise sus condiciones de validez.', 'For SPICE select the correct testbench or netlist and run ngspice or Xyce when available. Compare DC, AC or transient output with acceptance criteria. Generic template models are a starting point; replace them and review validity conditions for a specific process.') },
      { title: t('Use los adaptadores adecuados', 'Use the right adapters'), body: t('Xschem genera una netlist a partir de entradas compatibles; CACE caracteriza circuitos; openEMS estudia campos electromagnéticos con su configuración. Compruebe los requisitos de cada adaptador y conserve sus registros junto con las medidas.', 'Xschem generates a netlist from compatible inputs, CACE characterizes circuits and openEMS studies electromagnetic fields with its configuration. Check each adapter’s requirements and keep its logs with measurements.') },
    ], checkpoint: t('Puede explicar una forma de onda o una curva y relacionarla con una prueba que pasa o falla.', 'You can explain a waveform or curve and connect it to a passing or failing test.'),
    tip: t('Una simulación que termina sin errores puede tener estímulos insuficientes. Añada casos límite y comprobaciones de resultados, además de observar gráficos.', 'A simulation can finish without errors while having inadequate stimuli. Add boundary cases and output checks alongside visual inspection.'),
  },
  {
    id: 'physical', title: t('Generar GDSII y gestionar su turno', 'Generate GDSII and manage your turn'),
    summary: t('La implementación física convierte RTL digital compatible en geometría y reportes mediante LibreLane. Es el flujo más pesado del estudio y comparte una cola de ejecución entre usuarios.', 'Physical implementation converts supported digital RTL into geometry and reports through LibreLane. It is the studio’s heaviest flow and shares an execution queue among users.'),
    image: 'physical.jpg', callouts: [t('Etapas internas del flujo físico.', 'Internal physical-flow stages.'), t('Reloj, floorplan, utilización y envío.', 'Clock, floorplan, utilization and submission.'), t('Su posición, espera y flujos en ejecución.', 'Your position, wait and running flows.'), t('Cancelar el turno o abrir la guía.', 'Cancel the slot or open the guide.')],
    steps: [
      { title: t('Confirme el PDK y el reloj', 'Check the PDK and clock'), body: t('Use un PDK con adaptador físico preparado y bibliotecas instaladas. El puerto de reloj debe existir en el top. Establezca el período en ns: 25 ns corresponde a 40 MHz. Verifique RTL y testbench antes de reservar el turno.', 'Use a PDK with a ready physical adapter and installed libraries. The clock port must exist in the top module. Set its period in ns: 25 ns corresponds to 40 MHz. Verify RTL and the testbench before reserving a slot.') },
      { title: t('Especifique restricciones reales', 'Specify real constraints'), body: t('Si el proyecto incluye SDC, se usa su contenido. Revise reloj, retardos de I/O, cargas y excepciones de temporización de su interfaz. Sin SDC propio se genera una restricción básica de reloj; eso no describe por completo una interfaz real.', 'If the project includes SDC, its content is used. Review clocks, I/O delays, loads and timing exceptions for the interface. Without a project SDC a basic clock constraint is generated; this does not fully describe a real interface.') },
      { title: t('Empiece con floorplan automático', 'Start with automatic floorplan'), body: t('El modo automático calcula el dado a partir del área de celdas y la utilización objetivo. Reserve el tamaño manual para restricciones de integración o un floorplan definido. Una utilización demasiado alta puede dificultar colocación y ruteo; cambie una variable por ejecución.', 'Automatic mode sizes the die from cell area and target utilization. Reserve manual sizing for integration constraints or a defined floorplan. Excessive utilization can hinder placement and routing; change one variable per run.') },
      { title: t('Envíe una copia del diseño', 'Submit a design snapshot'), body: t('Pulse Ejecutar flujo completo RTL → GDSII. La tarjeta confirma que el trabajo está en cola e indica cuántos hay antes del suyo, su posición y el motivo de espera. Por defecto solo se ejecuta un flujo pesado a la vez. Una carga superior al umbral del 60 % de CPU también impide nuevas admisiones; memoria y disco tienen controles adicionales.', 'Click Run complete RTL → GDSII flow. The card confirms the queued job and shows jobs ahead, position and wait reason. By default only one heavy flow runs at a time. CPU load above the 60% threshold also prevents new admissions; memory and disk have additional checks.') },
      { title: t('Espere o cancele de forma segura', 'Wait or cancel safely'), body: t('La posición cuenta trabajos ejecutándose y trabajos anteriores en espera. No se promete una hora fija: la duración depende del diseño y los recursos. Puede cerrar o recargar y recuperar el turno al abrir el proyecto con su cuenta. Cancelar en cola elimina el turno sin iniciar herramientas; cancelar en ejecución espera a que se detengan antes de liberar recursos.', 'Position counts running jobs and earlier waiting jobs. A fixed completion time is not promised: duration depends on design and resources. Close or reload and recover the slot by opening the project with your account. Queued cancellation removes the slot without launching tools; running cancellation waits for tools to stop before releasing resources.') },
      { title: t('Siga etapas, no solo un contador', 'Follow stages, not just a timer'), body: t('Cuando comience verá tiempo de ejecución, etapa, CPU del ejecutor y memoria del proceso. Síntesis, floorplan, placement, CTS, routing y sign-off no duran lo mismo; una etapa silenciosa puede seguir trabajando. Abra Resultados al finalizar y revise las comprobaciones físicas.', 'Once started, the card shows execution time, stage, worker CPU and process memory. Synthesis, floorplan, placement, CTS, routing and sign-off have different durations; a quiet stage may still be working. Open Results afterwards and review physical checks.') },
    ], checkpoint: t('Su flujo tiene fuentes y SDC identificados, un turno confirmado y resultados descargables al terminar.', 'Your flow has identified sources and SDC, a confirmed slot and downloadable results on completion.'),
    tip: t('La cola protege recursos y reparte turnos; no acelera un diseño individual. Si el servidor se reinicia, los pendientes se recuperan y los que estaban ejecutándose se marcan interrumpidos para que los revise antes de volver a enviarlos.', 'The queue protects resources and distributes turns; it does not accelerate an individual design. After a server restart, waiting jobs recover and running jobs are marked interrupted for review before resubmission.'),
  },
  {
    id: 'results', title: t('Analizar, comparar y descargar evidencia', 'Analyze, compare and download evidence'),
    summary: t('Convierta los resultados en decisiones. Un archivo GDSII, un PASS de herramienta y una validación para fabricación son evidencias con alcances diferentes.', 'Turn results into decisions. A GDSII file, a tool PASS and fabrication validation are evidence with different scopes.'),
    image: 'results.jpg', callouts: [t('Métricas físicas y temporización.', 'Physical and timing metrics.'), t('Vistas del layout y controles de inspección.', 'Layout views and inspection controls.'), t('Estado de comprobaciones y evidencias.', 'Check status and evidence.')],
    steps: [
      { title: t('Revise métricas con unidades', 'Review metrics with units'), body: t('Abra Resultados. WNS es el peor slack y TNS agrega slack negativo; valores negativos señalan violaciones en el análisis reportado. Compare área, celdas y utilización. Un guion o dato desconocido significa falta de evidencia, no un cero ni un PASS.', 'Open Results. WNS is worst slack and TNS aggregates negative slack; negative values indicate violations in the reported analysis. Compare area, cells and utilization. A dash or unknown value means missing evidence, not zero or a PASS.') },
      { title: t('Inspeccione la implementación', 'Inspect the implementation'), body: t('Cambie entre vistas de celdas, densidad, rutas y 3D cuando exista un layout disponible. Use zoom y las capas para localizar congestión o distribución de celdas. La visualización ayuda a interpretar; consulte además reportes y netlists.', 'Switch between cells, density, routes and 3D when layout data is available. Use zoom and layers to locate congestion or cell distribution. Visualization aids interpretation; also inspect reports and netlists.') },
      { title: t('Lea el sign-off', 'Read sign-off'), body: t('Revise DRC, LVS, antenas y temporización según la evidencia disponible. PASS, FAIL y REVIEW se interpretan por comprobación. El portal produce evidencia de un bloque endurecido; un chip completo requiere integración, pads, encapsulado y los decks y aprobación de la fundición.', 'Review DRC, LVS, antennas and timing according to available evidence. Interpret PASS, FAIL and REVIEW per check. The portal provides evidence for a hardened block; a complete chip needs integration, pads, packaging and foundry decks and approval.') },
      { title: t('Descargue el paquete', 'Download the package'), body: t('Filtre artefactos por layout, netlist, temporización, reportes o configuración. Descargue el paquete ZIP cuando esté presente, además de los archivos que necesite. Los resultados físicos del servidor se conservan hasta 7 días o hasta que queden fuera de los 20 más recientes; descargue al terminar. Esos límites pueden configurarse en el servidor.', 'Filter artifacts by layout, netlist, timing, reports or configuration. Download the ZIP package when present and any needed files. Server physical results are kept for up to 7 days or until outside the 20 most recent results; download on completion. These limits are server-configurable.') },
      { title: t('Compare cambios controlados', 'Compare controlled changes'), body: t('Abra Historial y seleccione hasta cuatro ejecuciones. Compare métricas y estado usando la misma unidad y configuración comparable. El historial local conserva resúmenes de las últimas ocho ejecuciones, no todos los archivos; use exportaciones para su registro permanente.', 'Open History and select up to four runs. Compare metrics and status using consistent units and comparable configurations. Local history keeps summaries of the last eight runs, not every file; use exports for a permanent record.') },
    ], checkpoint: t('Puede justificar una decisión con una métrica, una configuración y su reporte descargado.', 'You can justify a decision with a metric, configuration and downloaded report.'),
    tip: t('Si el flujo terminó pero hay FAIL o REVIEW, atienda los bloqueos antes de tratar el resultado como listo. Conserve los logs de fallo para comparar después de corregir.', 'If the flow ended with FAIL or REVIEW, resolve blockers before treating it as ready. Keep failure logs for comparison after fixes.'),
  },
  {
    id: 'devices', title: t('Experimentar en el laboratorio de dispositivos', 'Experiment in the device lab'),
    summary: t('Explore desde una explicación guiada hasta barridos y análisis científicos. Los modelos analíticos y las animaciones se ejecutan en su navegador.', 'Explore from guided explanation to sweeps and scientific analysis. Analytical models and animations run in your browser.'),
    image: 'devices.jpg', callouts: [t('Dispositivo seleccionado y contexto del modelo.', 'Selected device and model context.'), t('Parámetros del experimento.', 'Experiment parameters.'), t('Curvas, métricas y controles de visualización.', 'Curves, metrics and visualization controls.')],
    steps: [
      { title: t('Elija nivel y dispositivo', 'Choose level and device'), body: t('Abra Laboratorio de dispositivos y seleccione Explorar, Aprender, Diseñar, Avanzado o Investigación. Use las familias y la búsqueda para localizar un dispositivo o una práctica. Los niveles añaden detalle sin cambiar la necesidad de entender supuestos y unidades.', 'Open Device Lab and select Explore, Learn, Design, Advanced or Research. Use families and search to find a device or practice. Levels add detail while retaining the need to understand assumptions and units.') },
      { title: t('Formule una hipótesis', 'Form a hypothesis'), body: t('Elija una guía o un experimento propio. Registre qué espera al cambiar temperatura, dopaje, geometría, tensión u otro parámetro. Ejecute el modelo y contraste las curvas con esa predicción.', 'Choose a guide or your own experiment. Record expected effects from temperature, doping, geometry, voltage or another parameter. Run the model and compare curves with that prediction.') },
      { title: t('Explore portadores y fabricación', 'Explore carriers and fabrication'), body: t('Los controles de animación permiten observar electrones y huecos en los dispositivos que cuentan con esa vista. Son representaciones educativas del mecanismo. El recorrido de fabricación relaciona pasos del proceso con experimentos; no ejecuta una receta industrial.', 'Animation controls show electrons and holes for devices with that view. These are educational representations of the mechanism. The fabrication walkthrough connects process steps to experiments; it does not run an industrial recipe.') },
      { title: t('Compare medidas y extraiga parámetros', 'Compare measurements and extract parameters'), body: t('En los niveles avanzados importe CSV con columnas x,y y opcionalmente sigma_y. Confirme unidades y el intervalo válido antes de ajustar una recta o extraer parámetros de una región exponencial. Revise residuos, incertidumbre y los supuestos del ajuste; un R² alto no prueba por sí solo un mecanismo físico.', 'At advanced levels import CSV with x,y and optional sigma_y columns. Check units and the valid range before fitting a line or extracting parameters from an exponential region. Review residuals, uncertainty and assumptions; high R² alone does not prove a physical mechanism.') },
      { title: t('Conserve el experimento', 'Keep the experiment'), body: t('Guarde notas, hipótesis y observaciones en el cuaderno. Exporte CSV de curvas, JSON reproducible y gráficas disponibles. Consulte las ecuaciones, comprobaciones y referencias del modelo antes de presentar resultados como evidencia científica.', 'Keep notes, hypotheses and observations in the notebook. Export curve CSV, reproducible JSON and available plots. Read model equations, checks and references before presenting results as scientific evidence.') },
    ], checkpoint: t('Su conclusión está vinculada a parámetros, unidades, hipótesis y límites del modelo.', 'Your conclusion connects parameters, units, hypothesis and model limits.'),
    tip: t('La consistencia numérica de un modelo no equivale a calibración con silicio medido. Ajuste parámetros y valide contra datos adecuados para investigación de un proceso concreto.', 'Numerical model consistency is not calibration against measured silicon. Fit parameters and validate against suitable data for research on a particular process.'),
  },
  {
    id: 'tcad', title: t('Usar DEVSIM en su computador', 'Run DEVSIM on your computer'),
    summary: t('El solver TCAD local resuelve el ejemplo de unión PN 1D en su equipo. El portal conecta con ese servicio local; DEVSIM no forma parte de la cola física del servidor.', 'The local TCAD solver runs the 1D PN junction example on your computer. The portal connects to this local service; DEVSIM does not use the server’s physical-flow queue.'),
    image: 'tcad.jpg', callouts: [t('Panel del solver para una unión PN avanzada.', 'Solver panel for an advanced PN junction.'), t('Detección, malla, ejecución y validación.', 'Detection, mesh, execution and validation.'), t('Instalación y permisos del equipo cliente.', 'Client computer installation and permissions.')],
    steps: [
      { title: t('Prepare el equipo cliente', 'Prepare the client computer'), body: t('Desde una copia de OpenSemiLab en su computador, use scripts/install-devsim-local.sh en Linux o scripts/install-devsim-local.ps1 en Windows. Las instrucciones del panel también muestran la instalación del paquete y el comando opensemilab-devsim.', 'From an OpenSemiLab copy on your computer, use scripts/install-devsim-local.sh on Linux or scripts/install-devsim-local.ps1 on Windows. The panel also shows package installation and the opensemilab-devsim command.') },
      { title: t('Autorice el origen del portal', 'Allow the portal origin'), body: t('Configure OPENSEMILAB_ALLOWED_ORIGINS con la URL de su portal al iniciar el servicio local. Abra una unión PN en Avanzado o Investigación y pulse Abrir DEVSIM local y validación de malla. Use Detectar DEVSIM y, si el navegador solicita acceso a la red local, autorícelo para este portal.', 'Set OPENSEMILAB_ALLOWED_ORIGINS to your portal URL when starting the local service. Open a PN junction in Advanced or Research and click Open local DEVSIM and mesh validation. Use Detect DEVSIM and allow local-network access for this portal if the browser requests it.') },
      { title: t('Resuelva y refine', 'Solve and refine'), body: t('Defina longitud y nodos de malla, ejecute TCAD local y compare con la referencia analítica. Validar 51 / 101 / 201 comprueba cómo cambia la solución al refinar y evalúa las pruebas implementadas. Descargue el paquete de validación para conservar entradas, versión y medidas.', 'Set length and mesh nodes, run local TCAD and compare with the analytical reference. Validate 51 / 101 / 201 examines changes under refinement and evaluates implemented checks. Download the validation bundle to preserve inputs, version and measurements.') },
      { title: t('Interprete su alcance', 'Interpret its scope'), body: t('El ejemplo es una unión de silicio abrupta, unidimensional y sin calibración específica de un proceso. Sus pruebas de convergencia y conservación ayudan a evaluar esta solución; no certifican todos los dispositivos ni la fabricación.', 'The example is an abrupt, one-dimensional silicon junction without process-specific calibration. Convergence and conservation tests help assess this solution; they do not certify all devices or fabrication.') },
    ], checkpoint: t('Detecta DEVSIM local y puede repetir una solución con su configuración y malla guardadas.', 'You can detect local DEVSIM and repeat a solution with saved configuration and mesh.'),
    tip: t('Si la detección falla, compruebe que el servicio sigue abierto en su computador y que el origen está autorizado. No instale ese solver en Azure ni en el B4 para resolver esta conexión del cliente.', 'If detection fails, check that the service is still running on your computer and the origin is allowed. Do not install this solver on Azure or B4 to address the client connection.'),
  },
  {
    id: 'pdks', title: t('PDK, herramientas y archivos privados', 'PDKs, tools and private files'),
    summary: t('Seleccione tecnología según el objetivo y la disponibilidad real de bibliotecas. Un inventario de archivos y un adaptador físico operativo representan niveles de preparación distintos.', 'Choose technology for your objective and actual library availability. A file inventory and an operational physical adapter represent different readiness levels.'),
    image: 'pdks.jpg', callouts: [t('Gestor e inventario de tecnologías.', 'Technology manager and inventory.'), t('Metadatos de los paquetes que desea importar.', 'Metadata for packages to import.'), t('Archivos y autorización para procesarlos.', 'Files and permission to process them.')],
    steps: [
      { title: t('Compruebe disponibilidad', 'Check availability'), body: t('Antes de ejecutar, abra Ver cobertura de herramientas dentro del proyecto y revise si el flujo está conectado. Algunas herramientas se ejecutan directamente, otras forman parte de un flujo y otras están disponibles sin una interfaz completa.', 'Before running, open View tool coverage inside the project and check flow connectivity. Some tools run directly, some are orchestrated within a flow and others are available without a full interface.') },
      { title: t('Importe solo archivos autorizados', 'Import authorized files'), body: t('En PDK propios registre nombre, versión, proceso y stack, adjunte los archivos y confirme que tiene permiso para utilizarlos. Revise el inventario y el diagnóstico; añadir archivos no garantiza que todos los formatos o reglas sean ejecutables.', 'Under Private PDKs register name, version, process and stack, attach files and confirm permission to use them. Review inventory and diagnostics; adding files does not guarantee all formats or rules are executable.') },
      { title: t('Prepare el adaptador necesario', 'Prepare the needed adapter'), body: t('Siga las opciones de conversión o incorporación de archivos del gestor. RTL→GDSII solo se habilita cuando el registro indica un adaptador físico válido y el ejecutor puede ver sus bibliotecas. Revise por separado estados de DRC, LVS y PEX.', 'Follow the manager’s conversion or additional-file options. RTL→GDSII is enabled only when the registry reports a valid physical adapter and the worker can access its libraries. Check DRC, LVS and PEX readiness separately.') },
      { title: t('Documente el proceso usado', 'Document the process used'), body: t('Asocie el PDK correcto al proyecto y conserve versión, stack y restricciones junto con las fuentes. Para comparar resultados entre tecnologías necesita condiciones comparables y modelos apropiados para cada una.', 'Associate the correct PDK with the project and preserve version, stack and constraints with sources. Comparing technologies requires comparable conditions and appropriate models for each.') },
    ], checkpoint: t('Sabe qué capacidades están listas, cuáles están pendientes y qué PDK usa cada ejecución.', 'You know which capabilities are ready or pending and which PDK each run uses.'),
    tip: t('La disponibilidad de una tecnología en el catálogo no implica aprobación de sus reglas para producción. Revise licencias y evidencias antes de compartir archivos del PDK.', 'A technology’s catalog entry does not imply production approval of its rules. Review licenses and evidence before sharing PDK files.'),
  },
  {
    id: 'admin', title: t('Administración, correo y comunidad', 'Administration, email and community'),
    summary: t('El panel Admin se muestra a cuentas con rol de administrador. Equipo, Galería, Términos y Privacidad permiten orientarse sobre el portal y su uso.', 'The Admin panel is shown to administrator accounts. Team, Gallery, Terms and Privacy provide context about the portal and its use.'),
    image: 'admin.jpg', callouts: [t('Sección de correo exclusiva del administrador.', 'Administrator-only mail section.'), t('Servidor SMTP, remitente y cifrado.', 'SMTP server, sender and encryption.'), t('Guardar y probar el envío.', 'Save and test delivery.')],
    steps: [
      { title: t('Acceda con el rol correcto', 'Use the correct role'), body: t('Abra Admin desde la navegación si su cuenta tiene ese rol. El panel muestra usuarios, proyectos y actividad. Una cuenta nueva tiene rol de usuario; un administrador autorizado debe conceder los permisos necesarios.', 'Open Admin from navigation if your account has that role. The panel shows users, projects and activity. New accounts have a user role; an authorized administrator must grant required permissions.') },
      { title: t('Configure correo saliente', 'Configure outgoing mail'), body: t('En Servidor de correo saliente active SMTP y escriba remitente, servidor, puerto, cifrado y credenciales de su proveedor. Al guardar, la contraseña queda cifrada y no se devuelve al navegador; dejar el campo vacío conserva la guardada.', 'Under Outgoing mail server enable SMTP and enter sender, server, port, encryption and provider credentials. The saved password is encrypted and not returned to the browser; leaving it empty preserves the existing password.') },
      { title: t('Compruebe entrega y acceso', 'Check delivery and access'), body: t('Guarde y pulse Probar conexión y envío. Confirme recepción del mensaje en la cuenta del administrador. Después pruebe el registro y la recuperación con una cuenta de usuario apropiada. No publique claves en el README ni en archivos del proyecto.', 'Save and click Test connection and delivery. Confirm receipt in the administrator’s inbox. Then test registration and recovery with a suitable user account. Keep secrets out of README and project files.') },
      { title: t('Use los controles administrativos', 'Use administrative controls'), body: t('Revise roles, verificación y estado activo de usuarios antes de cambiarlos. La eliminación de proyectos y los cambios de acceso afectan a otras personas: confirme que corresponden al objetivo. Los filtros y exportación CSV de actividad ayudan a entender el uso de herramientas.', 'Review user roles, verification and active state before changing them. Project deletion and access changes affect others; confirm they match the objective. Activity filters and CSV export help understand tool use.') },
      { title: t('Consulte los apartados del portal', 'Explore portal sections'), body: t('Equipo describe a sus responsables. Galería reúne ejemplos y referencias del laboratorio. Términos y Privacidad describen las condiciones de uso. Vuelva al Lab para continuar con su proyecto, manteniendo sus copias de fuentes y resultados.', 'Team describes project contributors. Gallery gathers laboratory examples and references. Terms and Privacy explain usage conditions. Return to the Lab to continue your project, keeping copies of sources and results.') },
    ], checkpoint: t('El administrador confirma un correo de prueba y los usuarios pueden completar su verificación.', 'An administrator confirms a test email and users can complete verification.'),
    tip: t('Los datos de estas capturas son ejemplos. Use sus propios datos de proveedor y cuentas; una contraseña mostrada como puntos no sirve para recuperarla.', 'Screenshot data is illustrative. Use your own provider and account details; password dots cannot recover a saved password.'),
  },
]
